import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { COUNTRIES } from './countries.js';

// ─── Image Map (generated by generate-images.mjs) ──────────────────────────

let IMAGE_MAP = {};
try {
  const module = await import('./image-map.js');
  IMAGE_MAP = module.IMAGE_MAP;
} catch {
  // Images not yet generated — panel will work without hero images
}

// ─── DOM ────────────────────────────────────────────────────────────────────

const container = document.getElementById('canvas-container');
const tooltip = document.getElementById('tooltip');
const panel = document.getElementById('country-panel');
const panelClose = document.getElementById('panel-close');
const panelHero = document.getElementById('panel-hero');
const panelRegion = document.getElementById('panel-region');
const panelCountryName = document.getElementById('panel-country-name');
const panelCountryDesc = document.getElementById('panel-country-desc');
const panelOffers = document.getElementById('panel-offers');

// Loading
const loadingOverlay = document.createElement('div');
loadingOverlay.className = 'loading-overlay';
loadingOverlay.innerHTML = '<div class="loading-spinner"></div><div class="loading-text">Loading</div>';
document.body.appendChild(loadingOverlay);

// ─── Scene ──────────────────────────────────────────────────────────────────

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000);
camera.position.set(0, 0.4, 3.0);

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.3;
container.appendChild(renderer.domElement);

// Controls
const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.05;
controls.enablePan = false;
controls.minDistance = 1.2;
controls.maxDistance = 5;
controls.autoRotate = true;
controls.autoRotateSpeed = 0.35;

// ─── Stars ──────────────────────────────────────────────────────────────────

(function createStars() {
  const count = 6000;
  const positions = new Float32Array(count * 3);
  for (let i = 0; i < count; i++) {
    const r = 40 + Math.random() * 160;
    const theta = Math.random() * Math.PI * 2;
    const phi = Math.acos(2 * Math.random() - 1);
    positions[i * 3] = r * Math.sin(phi) * Math.cos(theta);
    positions[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta);
    positions[i * 3 + 2] = r * Math.cos(phi);
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  scene.add(new THREE.Points(geo, new THREE.PointsMaterial({
    color: 0xffffff, size: 0.06, sizeAttenuation: true, transparent: true, opacity: 0.6,
  })));
})();

// ─── Lighting ───────────────────────────────────────────────────────────────

scene.add(new THREE.AmbientLight(0x334466, 0.5));

const sunLight = new THREE.DirectionalLight(0xfff8ee, 2.8);
sunLight.position.set(5, 3, 5);
scene.add(sunLight);

const fillLight = new THREE.DirectionalLight(0x4488cc, 0.3);
fillLight.position.set(-4, -1, -4);
scene.add(fillLight);

// ─── Earth ──────────────────────────────────────────────────────────────────

const GLOBE_RADIUS = 1;
const globeGroup = new THREE.Group();
scene.add(globeGroup);

const textureLoader = new THREE.TextureLoader();

// NASA Blue Marble textures via three-globe CDN
const earthColorUrl = 'https://unpkg.com/three-globe@2.31.1/example/img/earth-blue-marble.jpg';
const earthBumpUrl = 'https://unpkg.com/three-globe@2.31.1/example/img/earth-topology.png';
const earthSpecUrl = 'https://unpkg.com/three-globe@2.31.1/example/img/earth-water.png';

let texturesLoaded = 0;
const totalTextures = 3;

function onTextureLoad() {
  texturesLoaded++;
  if (texturesLoaded >= totalTextures) {
    loadGeoData();
  }
}

function onTextureError() { onTextureLoad(); } // Continue loading even if a texture fails
const earthColor = textureLoader.load(earthColorUrl, onTextureLoad, undefined, onTextureError);
const earthBump = textureLoader.load(earthBumpUrl, onTextureLoad, undefined, onTextureError);
const earthSpec = textureLoader.load(earthSpecUrl, onTextureLoad, undefined, onTextureError);

const earthGeometry = new THREE.SphereGeometry(GLOBE_RADIUS, 128, 64);
const earthMaterial = new THREE.MeshPhongMaterial({
  map: earthColor,
  bumpMap: earthBump,
  bumpScale: 0.015,
  specularMap: earthSpec,
  specular: new THREE.Color(0x222244),
  shininess: 15,
});

const earthMesh = new THREE.Mesh(earthGeometry, earthMaterial);
globeGroup.add(earthMesh);

// Atmosphere
const atmosphereMaterial = new THREE.ShaderMaterial({
  vertexShader: `
    varying vec3 vNormal;
    varying vec3 vPosition;
    void main() {
      vNormal = normalize(normalMatrix * normal);
      vPosition = (modelViewMatrix * vec4(position, 1.0)).xyz;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  fragmentShader: `
    varying vec3 vNormal;
    varying vec3 vPosition;
    void main() {
      vec3 viewDir = normalize(-vPosition);
      float fresnel = 1.0 - dot(viewDir, vNormal);
      fresnel = pow(fresnel, 3.5);
      vec3 color = mix(vec3(0.15, 0.4, 0.9), vec3(0.35, 0.65, 1.0), fresnel);
      gl_FragColor = vec4(color, fresnel * 0.3);
    }
  `,
  transparent: true,
  side: THREE.FrontSide,
  depthWrite: false,
});
globeGroup.add(new THREE.Mesh(
  new THREE.SphereGeometry(GLOBE_RADIUS * 1.012, 64, 32),
  atmosphereMaterial
));

// ─── Country Borders ────────────────────────────────────────────────────────

const countryMeshes = [];
const countryBorders = {};
let hoveredCountry = null;
const countriesGroup = new THREE.Group();
globeGroup.add(countriesGroup);

// ISO 3166 numeric to name mapping for world-atlas
const COUNTRY_ID_MAP = {
  '004': 'Afghanistan', '008': 'Albania', '012': 'Algeria', '024': 'Angola',
  '032': 'Argentina', '036': 'Australia', '040': 'Austria', '050': 'Bangladesh',
  '056': 'Belgium', '064': 'Bhutan', '068': 'Bolivia', '070': 'Bosnia and Herzegovina',
  '072': 'Botswana', '076': 'Brazil', '100': 'Bulgaria', '104': 'Myanmar',
  '116': 'Cambodia', '120': 'Cameroon', '124': 'Canada', '140': 'Central African Republic',
  '144': 'Sri Lanka', '148': 'Chad', '152': 'Chile', '156': 'China',
  '170': 'Colombia', '178': 'Republic of the Congo', '180': 'Democratic Republic of the Congo',
  '188': 'Costa Rica', '191': 'Croatia', '192': 'Cuba', '196': 'Cyprus',
  '203': 'Czech Republic', '208': 'Denmark', '214': 'Dominican Republic',
  '218': 'Ecuador', '818': 'Egypt', '222': 'El Salvador', '226': 'Equatorial Guinea',
  '232': 'Eritrea', '233': 'Estonia', '231': 'Ethiopia', '246': 'Finland',
  '250': 'France', '266': 'Gabon', '270': 'Gambia', '268': 'Georgia',
  '276': 'Germany', '288': 'Ghana', '300': 'Greece', '320': 'Guatemala',
  '324': 'Guinea', '328': 'Guyana', '332': 'Haiti', '340': 'Honduras',
  '348': 'Hungary', '352': 'Iceland', '356': 'India', '360': 'Indonesia',
  '364': 'Iran', '368': 'Iraq', '372': 'Ireland', '376': 'Israel',
  '380': 'Italy', '384': 'Ivory Coast', '388': 'Jamaica', '392': 'Japan',
  '400': 'Jordan', '398': 'Kazakhstan', '404': 'Kenya', '408': 'North Korea',
  '410': 'South Korea', '414': 'Kuwait', '417': 'Kyrgyzstan', '418': 'Laos',
  '422': 'Lebanon', '426': 'Lesotho', '430': 'Liberia', '434': 'Libya',
  '440': 'Lithuania', '442': 'Luxembourg', '450': 'Madagascar', '454': 'Malawi',
  '458': 'Malaysia', '462': 'Maldives', '466': 'Mali', '478': 'Mauritania',
  '484': 'Mexico', '496': 'Mongolia', '499': 'Montenegro', '504': 'Morocco',
  '508': 'Mozambique', '516': 'Namibia', '524': 'Nepal', '528': 'Netherlands',
  '540': 'New Caledonia', '554': 'New Zealand', '558': 'Nicaragua', '562': 'Niger',
  '566': 'Nigeria', '578': 'Norway', '512': 'Oman', '586': 'Pakistan',
  '591': 'Panama', '598': 'Papua New Guinea', '600': 'Paraguay', '604': 'Peru',
  '608': 'Philippines', '616': 'Poland', '620': 'Portugal', '630': 'Puerto Rico',
  '634': 'Qatar', '642': 'Romania', '643': 'Russia', '646': 'Rwanda',
  '682': 'Saudi Arabia', '686': 'Senegal', '688': 'Serbia', '694': 'Sierra Leone',
  '702': 'Singapore', '703': 'Slovakia', '705': 'Slovenia', '706': 'Somalia',
  '710': 'South Africa', '724': 'Spain', '736': 'Sudan', '740': 'Suriname',
  '748': 'Eswatini', '752': 'Sweden', '756': 'Switzerland', '760': 'Syria',
  '762': 'Tajikistan', '764': 'Thailand', '780': 'Trinidad and Tobago',
  '788': 'Tunisia', '792': 'Turkey', '795': 'Turkmenistan', '800': 'Uganda',
  '804': 'Ukraine', '784': 'United Arab Emirates', '826': 'United Kingdom',
  '840': 'United States of America', '858': 'Uruguay', '860': 'Uzbekistan',
  '862': 'Venezuela', '704': 'Vietnam', '887': 'Yemen', '894': 'Zambia',
  '716': 'Zimbabwe', '728': 'South Sudan', '174': 'Comoros',
  '834': 'Tanzania',
};

function latLngToVec3(lat, lng, r) {
  const phi = (90 - lat) * (Math.PI / 180);
  const theta = (lng + 180) * (Math.PI / 180);
  return new THREE.Vector3(
    -r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta)
  );
}

function createBorderLine(coords, radius, color) {
  const points = coords.map(c => latLngToVec3(c[1], c[0], radius));
  const geo = new THREE.BufferGeometry().setFromPoints(points);
  return new THREE.Line(geo, new THREE.LineBasicMaterial({
    color, transparent: true, opacity: 0.35,
  }));
}

function createPickMesh(coords, name, radius) {
  const points = coords.map(c => latLngToVec3(c[1], c[0], radius + 0.003));
  if (points.length < 3) return null;

  const center = new THREE.Vector3();
  points.forEach(p => center.add(p));
  center.divideScalar(points.length);

  const verts = [];
  for (let i = 0; i < points.length - 1; i++) {
    verts.push(center.x, center.y, center.z);
    verts.push(points[i].x, points[i].y, points[i].z);
    verts.push(points[i + 1].x, points[i + 1].y, points[i + 1].z);
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(verts, 3));
  geo.computeVertexNormals();

  const mesh = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({
    color: 0xffffff, transparent: true, opacity: 0, side: THREE.DoubleSide, depthWrite: false,
  }));
  mesh.userData.countryName = name;
  return mesh;
}

async function loadGeoData() {
  try {
    const res = await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json');
    const topo = await res.json();
    const features = topojson.feature(topo, topo.objects.countries).features;

    for (const feature of features) {
      const name = COUNTRY_ID_MAP[feature.id] || null;
      if (!name) continue;

      const isFeatured = name in COUNTRIES;
      const borderColor = isFeatured ? 0x8a9aaa : 0x1e3f55;

      const processRing = (ring) => {
        const line = createBorderLine(ring, GLOBE_RADIUS + 0.001, borderColor);
        line.userData.countryName = name;
        countriesGroup.add(line);

        if (!countryBorders[name]) countryBorders[name] = [];
        countryBorders[name].push(line);

        if (isFeatured) {
          const mesh = createPickMesh(ring, name, GLOBE_RADIUS);
          if (mesh) {
            countriesGroup.add(mesh);
            countryMeshes.push(mesh);
          }
        }
      };

      const geom = feature.geometry;
      if (geom.type === 'Polygon') {
        geom.coordinates.forEach(processRing);
      } else if (geom.type === 'MultiPolygon') {
        geom.coordinates.forEach(poly => poly.forEach(processRing));
      }
    }

    // Fade out loading
    loadingOverlay.classList.add('fade-out');
    setTimeout(() => loadingOverlay.remove(), 800);
  } catch (err) {
    console.error('Failed to load geo data:', err);
    loadingOverlay.querySelector('.loading-text').textContent = 'Failed to load — please refresh';
  }
}

// ─── Location Markers — thin vertical pins ───────────────────────────────

const COUNTRY_COORDS = {
  'France': [2.35, 48.86], 'Italy': [12.49, 41.9], 'Spain': [-3.7, 40.42],
  'Portugal': [-9.14, 38.74], 'Greece': [23.73, 37.97], 'Switzerland': [7.45, 46.95],
  'Croatia': [15.98, 45.81], 'Iceland': [-21.9, 64.15], 'Norway': [10.75, 59.91],
  'Ireland': [-6.26, 53.35], 'Czech Republic': [14.42, 50.08], 'Turkey': [28.98, 41.01],
  'Germany': [10.45, 51.17], 'United Kingdom': [-0.12, 51.51], 'Netherlands': [4.9, 52.37],
  'Austria': [13.4, 47.07], 'Sweden': [18.07, 59.33], 'Denmark': [12.57, 55.68],
  'Poland': [19.94, 50.06], 'Hungary': [19.04, 47.5], 'Belgium': [4.35, 50.85],
  'Finland': [24.94, 60.17], 'Montenegro': [18.77, 42.44], 'Slovenia': [14.51, 46.06],
  'Japan': [139.69, 35.69], 'Thailand': [100.5, 13.76], 'Vietnam': [105.85, 21.03],
  'Indonesia': [106.85, -6.21], 'India': [77.21, 28.61], 'South Korea': [126.98, 37.57],
  'Sri Lanka': [79.86, 6.93], 'Nepal': [85.32, 27.72], 'Maldives': [73.51, 4.18],
  'United States of America': [-98.58, 39.83], 'Mexico': [-99.13, 19.43],
  'Brazil': [-47.93, -15.78], 'Argentina': [-58.38, -34.6], 'Peru': [-77.04, -12.05],
  'Costa Rica': [-84.09, 9.93], 'Colombia': [-74.07, 4.71], 'Morocco': [-6.85, 33.97],
  'South Africa': [28.04, -26.2], 'Kenya': [36.82, -1.29], 'Tanzania': [35.74, -6.16],
  'Egypt': [31.24, 30.04], 'Jordan': [35.95, 31.95], 'United Arab Emirates': [54.37, 24.45],
  'Australia': [149.13, -35.28], 'New Zealand': [174.78, -41.29],
};

const markerGroup = new THREE.Group();
globeGroup.add(markerGroup);

function createLocationMarkers() {
  const PIN_HEIGHT = 0.04;

  for (const [name, [lng, lat]] of Object.entries(COUNTRY_COORDS)) {
    if (!(name in COUNTRIES)) continue;

    const base = latLngToVec3(lat, lng, GLOBE_RADIUS + 0.002);
    const tip = latLngToVec3(lat, lng, GLOBE_RADIUS + 0.002 + PIN_HEIGHT);
    const normal = base.clone().normalize();

    // Thin line stem
    const stemGeo = new THREE.BufferGeometry().setFromPoints([base, tip]);
    const stem = new THREE.Line(stemGeo, new THREE.LineBasicMaterial({
      color: 0xffffff, transparent: true, opacity: 0.5,
    }));
    stem.renderOrder = 2;
    markerGroup.add(stem);

    // Small diamond at the tip (rotated square)
    const diamondSize = 0.005;
    const diamondGeo = new THREE.BufferGeometry();
    const up = normal.clone();
    const right = new THREE.Vector3().crossVectors(up, new THREE.Vector3(0, 1, 0)).normalize();
    if (right.length() < 0.01) right.crossVectors(up, new THREE.Vector3(1, 0, 0)).normalize();
    const fwd = new THREE.Vector3().crossVectors(right, up).normalize();

    const d = diamondSize;
    const verts = new Float32Array([
      // top triangle
      tip.x + up.x * d, tip.y + up.y * d, tip.z + up.z * d,
      tip.x + right.x * d * 0.5, tip.y + right.y * d * 0.5, tip.z + right.z * d * 0.5,
      tip.x - right.x * d * 0.5, tip.y - right.y * d * 0.5, tip.z - right.z * d * 0.5,
      // bottom triangle
      tip.x - up.x * d, tip.y - up.y * d, tip.z - up.z * d,
      tip.x + right.x * d * 0.5, tip.y + right.y * d * 0.5, tip.z + right.z * d * 0.5,
      tip.x - right.x * d * 0.5, tip.y - right.y * d * 0.5, tip.z - right.z * d * 0.5,
      // front-back triangles
      tip.x + up.x * d, tip.y + up.y * d, tip.z + up.z * d,
      tip.x + fwd.x * d * 0.5, tip.y + fwd.y * d * 0.5, tip.z + fwd.z * d * 0.5,
      tip.x - fwd.x * d * 0.5, tip.y - fwd.y * d * 0.5, tip.z - fwd.z * d * 0.5,
      tip.x - up.x * d, tip.y - up.y * d, tip.z - up.z * d,
      tip.x + fwd.x * d * 0.5, tip.y + fwd.y * d * 0.5, tip.z + fwd.z * d * 0.5,
      tip.x - fwd.x * d * 0.5, tip.y - fwd.y * d * 0.5, tip.z - fwd.z * d * 0.5,
    ]);
    diamondGeo.setAttribute('position', new THREE.BufferAttribute(verts, 3));
    diamondGeo.computeVertexNormals();

    const diamond = new THREE.Mesh(diamondGeo, new THREE.MeshBasicMaterial({
      color: 0xffffff, transparent: true, opacity: 0.85, side: THREE.DoubleSide, depthTest: false,
    }));
    diamond.renderOrder = 2;
    markerGroup.add(diamond);
  }
}

createLocationMarkers();

// ─── Social Proof Data ───────────────────────────────────────────────────

function getCountryRating(name) {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash) + name.charCodeAt(i);
  const rating = 4.5 + (Math.abs(hash) % 5) / 10;
  const reviews = 800 + (Math.abs(hash >> 4) % 4200);
  return { rating: Math.round(rating * 10) / 10, reviews };
}

function getScarcityBadge(offerIndex, countryName) {
  let hash = 0;
  for (let i = 0; i < countryName.length; i++) hash = ((hash << 5) - hash) + countryName.charCodeAt(i);
  const badges = ['Limited spots', 'Selling fast', 'Popular choice', null, null];
  return badges[(Math.abs(hash >> (offerIndex * 3)) % badges.length)];
}

function getOriginalPrice(price) {
  const num = parseInt(price.replace(/[^0-9]/g, ''));
  if (isNaN(num)) return null;
  const markup = Math.round(num * (1.15 + Math.random() * 0.2));
  return '$' + markup.toLocaleString();
}

// ─── Page Overlays (declared early for use in openPanel) ─────────────────

const pageOverlays = {
  destinations: document.getElementById('page-destinations'),
  experiences: document.getElementById('page-experiences'),
  journal: document.getElementById('page-journal'),
  article: document.getElementById('page-article'),
  about: document.getElementById('page-about'),
};

const bookPanel = document.getElementById('page-book');
const bookPanelClose = document.getElementById('book-panel-close');

// ─── Booking Modal ───────────────────────────────────────────────────────

const bookingModal = document.getElementById('booking-modal');
const bookingForm = document.getElementById('booking-form');
const bookingSuccess = document.getElementById('booking-success');
const bookingModalClose = document.getElementById('booking-modal-close');
const bookingModalTag = document.getElementById('booking-modal-tag');
const bookingModalTitle = document.getElementById('booking-modal-title');
const bookingModalSubtitle = document.getElementById('booking-modal-subtitle');

let currentBookingContext = {};

function openBookingModal(countryName, offerTitle, offerType, offerPrice) {
  currentBookingContext = { countryName, offerTitle, offerType, offerPrice };
  bookingModalTag.textContent = `${offerType} · ${countryName}`;
  bookingModalTitle.textContent = offerTitle;
  bookingModalSubtitle.textContent = `From ${offerPrice} — reserve your spot with no commitment.`;
  bookingForm.style.display = '';
  bookingSuccess.classList.remove('show');
  bookingForm.reset();
  bookingModal.classList.add('open');
  bookingModal.setAttribute('aria-hidden', 'false');
}

function closeBookingModal() {
  bookingModal.classList.remove('open');
  bookingModal.setAttribute('aria-hidden', 'true');
}

bookingModalClose.addEventListener('click', closeBookingModal);
bookingModal.querySelector('.booking-modal-backdrop').addEventListener('click', closeBookingModal);
document.addEventListener('keydown', e => { if (e.key === 'Escape' && bookingModal.classList.contains('open')) closeBookingModal(); });

bookingForm.addEventListener('submit', (e) => {
  e.preventDefault();
  const formData = new FormData(bookingForm);
  const data = Object.fromEntries(formData.entries());
  data.country = currentBookingContext.countryName;
  data.offer = currentBookingContext.offerTitle;
  data.offerType = currentBookingContext.offerType;
  console.log('Booking request:', data);
  bookingForm.style.display = 'none';
  bookingSuccess.classList.add('show');
  setTimeout(closeBookingModal, 3000);
});

// ─── Interaction ────────────────────────────────────────────────────────────

const raycaster = new THREE.Raycaster();
const mouse = new THREE.Vector2();
const mousePos = { x: 0, y: 0 };

function onPointerMove(e) {
  mouse.x = (e.clientX / window.innerWidth) * 2 - 1;
  mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
  mousePos.x = e.clientX;
  mousePos.y = e.clientY;
}

function highlightCountry(name) {
  if (hoveredCountry === name) return;
  if (hoveredCountry) clearHighlight(hoveredCountry);
  hoveredCountry = name;

  if (!countryBorders[name]) return;

  for (const line of countryBorders[name]) {
    line.material.color.setHex(0xdde0e4);
    line.material.opacity = 0.9;
    line.scale.setScalar(1.008);
  }
  for (const mesh of countryMeshes) {
    if (mesh.userData.countryName === name) mesh.material.opacity = 0.1;
  }

  const data = COUNTRIES[name];
  if (data) {
    tooltip.innerHTML = `${name}<span class="tooltip-region">${data.region}</span>`;
    tooltip.classList.add('visible');
    document.body.style.cursor = 'pointer';
  }
}

function clearHighlight(name) {
  if (!countryBorders[name]) return;
  const isFeatured = name in COUNTRIES;

  for (const line of countryBorders[name]) {
    line.material.color.setHex(isFeatured ? 0x8a9aaa : 0x1e3f55);
    line.material.opacity = 0.35;
    line.scale.setScalar(1);
  }
  for (const mesh of countryMeshes) {
    if (mesh.userData.countryName === name) mesh.material.opacity = 0;
  }
  tooltip.classList.remove('visible');
  document.body.style.cursor = 'grab';
}

function onPointerDown(e) {
  onPointerDown._startX = e.clientX;
  onPointerDown._startY = e.clientY;
}

function onPointerUp(e) {
  const dx = Math.abs(e.clientX - (onPointerDown._startX || 0));
  const dy = Math.abs(e.clientY - (onPointerDown._startY || 0));
  if (dx > 5 || dy > 5) return;
  if (hoveredCountry && hoveredCountry in COUNTRIES) {
    openPanel(hoveredCountry);
  }
}

function dimGlobe(dim) {
  container.classList.toggle('dimmed', dim);
}

function staggerPanelContent() {
  const els = panel.querySelectorAll('.panel-hero, .panel-desc, .panel-social-proof, .offer-card, .panel-sticky-cta');
  els.forEach((el, i) => {
    el.classList.add('panel-stagger');
    el.classList.remove('visible');
    setTimeout(() => el.classList.add('visible'), 80 * (i + 1));
  });
}

function openPanel(name) {
  const data = COUNTRIES[name];
  if (!data) return;

  // Close any open page panels and book panel
  Object.values(pageOverlays).forEach(p => p.classList.remove('open'));
  bookPanel.classList.remove('open');

  panelRegion.textContent = data.region;
  panelCountryName.textContent = name;
  panelCountryDesc.textContent = data.desc;

  // Hero image
  const existingImg = panelHero.querySelector('img');
  if (existingImg) existingImg.remove();

  const imagePath = IMAGE_MAP[name];
  if (imagePath) {
    const img = document.createElement('img');
    img.src = imagePath;
    img.alt = name;
    img.loading = 'eager';
    img.onerror = () => { panelHero.style.display = 'none'; };
    panelHero.insertBefore(img, panelHero.firstChild);
    panelHero.style.display = '';
  } else {
    panelHero.style.display = 'none';
  }

  // Social proof
  const { rating, reviews } = getCountryRating(name);
  const fullStars = Math.floor(rating);
  const hasHalf = rating % 1 >= 0.4;
  let starsHtml = '';
  for (let i = 0; i < 5; i++) {
    if (i < fullStars) starsHtml += '<span class="panel-star">&#9733;</span>';
    else if (i === fullStars && hasHalf) starsHtml += '<span class="panel-star">&#9733;</span>';
    else starsHtml += '<span class="panel-star empty">&#9733;</span>';
  }

  panel.querySelectorAll('.panel-social-proof, .panel-sticky-cta').forEach(el => el.remove());

  const socialProof = document.createElement('div');
  socialProof.className = 'panel-social-proof';
  socialProof.innerHTML = `
    <div class="panel-stars">${starsHtml}</div>
    <span class="panel-rating-text">${rating}</span>
    <span class="panel-review-count">${reviews.toLocaleString()} traveler reviews</span>
  `;
  panelCountryDesc.parentNode.insertBefore(socialProof, panelCountryDesc.nextSibling);

  // Offer cards
  panelOffers.innerHTML = data.offers.map((offer, i) => {
    const badge = getScarcityBadge(i, name);
    const originalPrice = getOriginalPrice(offer.price);
    const badgeHtml = badge ? `<span class="offer-card-badge">${badge}</span>` : '';
    const origHtml = originalPrice ? `<span class="offer-card-original-price">${originalPrice}</span>` : '';

    return `
      <article class="offer-card">
        <div class="offer-card-header">
          <span class="offer-card-type">${offer.type}</span>
          ${badgeHtml}
          <div class="offer-card-price-wrap">
            ${origHtml}
            <span class="offer-card-price">${offer.price} <span>/ ${offer.per}</span></span>
          </div>
        </div>
        <h3>${offer.title}</h3>
        <p class="offer-card-desc">${offer.desc}</p>
        <div class="offer-card-details">
          ${offer.details.map(d => `<span class="offer-detail">${d}</span>`).join('')}
        </div>
        <button class="offer-card-book" data-country="${name}" data-title="${offer.title}" data-type="${offer.type}" data-price="${offer.price}">Book now</button>
      </article>
    `;
  }).join('');

  panelOffers.querySelectorAll('.offer-card-book').forEach(btn => {
    btn.addEventListener('click', () => {
      openBookingModal(btn.dataset.country, btn.dataset.title, btn.dataset.type, btn.dataset.price);
    });
  });

  // Sticky CTA
  const stickyCta = document.createElement('div');
  stickyCta.className = 'panel-sticky-cta';
  stickyCta.innerHTML = `<button class="panel-sticky-btn">Book your ${name} trip</button>`;
  panel.querySelector('.panel-body').appendChild(stickyCta);
  stickyCta.querySelector('.panel-sticky-btn').addEventListener('click', () => {
    const firstOffer = data.offers[0];
    openBookingModal(name, firstOffer.title, firstOffer.type, firstOffer.price);
  });

  panel.classList.add('open');
  dimGlobe(true);
  controls.autoRotate = false;

  // Stagger content after panel slides in
  setTimeout(staggerPanelContent, 80);
}

function closePanel() {
  panel.classList.remove('open');
  const anyPageOpen = Object.values(pageOverlays).some(p => p.classList.contains('open'));
  const bookOpen = bookPanel.classList.contains('open');
  if (!anyPageOpen && !bookOpen) {
    dimGlobe(false);
    setTimeout(() => { controls.autoRotate = true; }, 300);
  }
}

panelClose.addEventListener('click', closePanel);
document.addEventListener('keydown', e => { if (e.key === 'Escape') closePanel(); });

window.addEventListener('pointermove', onPointerMove);
window.addEventListener('pointerdown', onPointerDown);
window.addEventListener('pointerup', onPointerUp);

// ─── Search & Fly-To ─────────────────────────────────────────────────────

const searchInput = document.getElementById('search-input');
const searchResults = document.getElementById('search-results');
const searchKbd = document.getElementById('search-kbd');

const countryNames = Object.keys(COUNTRIES);
let searchActiveIndex = -1;

// Keyboard shortcut: "/" to focus search
document.addEventListener('keydown', (e) => {
  if (e.key === '/' && document.activeElement !== searchInput &&
      !bookingModal.classList.contains('open')) {
    e.preventDefault();
    searchInput.focus();
  }
});

searchInput.addEventListener('focus', () => {
  searchKbd.style.display = 'none';
  controls.autoRotate = false;
});

searchInput.addEventListener('blur', () => {
  searchKbd.style.display = '';
  setTimeout(() => {
    searchResults.classList.remove('open');
    searchActiveIndex = -1;
    if (!panel.classList.contains('open')) controls.autoRotate = true;
  }, 200);
});

searchInput.addEventListener('input', () => {
  const q = searchInput.value.trim().toLowerCase();
  searchActiveIndex = -1;

  if (!q) {
    searchResults.classList.remove('open');
    searchResults.innerHTML = '';
    return;
  }

  const matches = countryNames.filter(n => n.toLowerCase().includes(q)).slice(0, 6);

  if (matches.length === 0) {
    searchResults.innerHTML = '<li class="search-no-results">No destinations found</li>';
    searchResults.classList.add('open');
    return;
  }

  searchResults.innerHTML = matches.map((name, i) => {
    const data = COUNTRIES[name];
    const idx = name.toLowerCase().indexOf(q);
    const highlighted = name.slice(0, idx) + '<mark>' + name.slice(idx, idx + q.length) + '</mark>' + name.slice(idx + q.length);
    return `<li class="search-result-item" role="option" data-name="${name}" data-index="${i}">
      <span class="search-result-name">${highlighted}</span>
      <span class="search-result-region">${data.region}</span>
    </li>`;
  }).join('');

  searchResults.classList.add('open');
});

// Event delegation for search results (avoids re-attaching listeners on each input)
searchResults.addEventListener('mousedown', (e) => {
  const item = e.target.closest('.search-result-item');
  if (!item) return;
  e.preventDefault();
  selectSearchResult(item.dataset.name);
});

searchInput.addEventListener('keydown', (e) => {
  const items = searchResults.querySelectorAll('.search-result-item');
  if (!items.length) return;

  if (e.key === 'ArrowDown') {
    e.preventDefault();
    searchActiveIndex = Math.min(searchActiveIndex + 1, items.length - 1);
    updateActiveResult(items);
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    searchActiveIndex = Math.max(searchActiveIndex - 1, 0);
    updateActiveResult(items);
  } else if (e.key === 'Enter' && searchActiveIndex >= 0) {
    e.preventDefault();
    selectSearchResult(items[searchActiveIndex].dataset.name);
  } else if (e.key === 'Escape') {
    searchInput.blur();
  }
});

function updateActiveResult(items) {
  items.forEach((item, i) => {
    item.classList.toggle('active', i === searchActiveIndex);
  });
}

function selectSearchResult(name) {
  searchInput.value = '';
  searchResults.classList.remove('open');
  searchResults.innerHTML = '';
  searchInput.blur();

  flyToCountry(name);
}

// ─── Fly-To Animation ────────────────────────────────────────────────────

let flyAnimation = null;

function flyToCountry(name) {
  const coords = COUNTRY_COORDS[name];
  if (!coords) return;

  const [lng, lat] = coords;

  // We need to position the camera so the target country faces the camera.
  // The globe rotates via globeGroup — we animate the camera around the globe instead.
  const targetCamPos = latLngToVec3(lat, lng, 2.4); // distance from center

  const startPos = camera.position.clone();
  const startTarget = controls.target.clone();
  const endTarget = new THREE.Vector3(0, 0, 0);

  // Cancel previous animation
  if (flyAnimation) cancelAnimationFrame(flyAnimation);
  controls.autoRotate = false;

  const duration = 1200; // ms
  const startTime = performance.now();

  // Highlight the country immediately
  highlightCountry(name);

  function animateFly(now) {
    const elapsed = now - startTime;
    let t = Math.min(elapsed / duration, 1);
    // Ease-out cubic
    t = 1 - Math.pow(1 - t, 3);

    camera.position.lerpVectors(startPos, targetCamPos, t);
    controls.target.lerpVectors(startTarget, endTarget, t);
    controls.update();

    if (t < 1) {
      flyAnimation = requestAnimationFrame(animateFly);
    } else {
      flyAnimation = null;
      // Open the panel after arrival
      if (name in COUNTRIES) {
        openPanel(name);
      }
    }
  }

  flyAnimation = requestAnimationFrame(animateFly);
}

// ─── Render Loop ────────────────────────────────────────────────────────────

function animate() {
  requestAnimationFrame(animate);
  controls.update();

  raycaster.setFromCamera(mouse, camera);
  const hits = raycaster.intersectObjects(countryMeshes);

  if (hits.length > 0) {
    const name = hits[0].object.userData.countryName;
    if (name in COUNTRIES) {
      highlightCountry(name);
      tooltip.style.transform = `translate(${mousePos.x + 14}px, ${mousePos.y - 14}px)`;
    }
  } else if (hoveredCountry) {
    clearHighlight(hoveredCountry);
    hoveredCountry = null;
  }

  renderer.render(scene, camera);
}

animate();

// ─── Resize ─────────────────────────────────────────────────────────────────

window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

// ─── Navigation ──────────────────────────────────────────────────────────

// Populate destination select in Book a Trip form
const bookDestSelect = document.getElementById('book-destination');
if (bookDestSelect) {
  const regions = {};
  for (const [name, data] of Object.entries(COUNTRIES)) {
    if (!regions[data.region]) regions[data.region] = [];
    regions[data.region].push(name);
  }
  for (const [region, names] of Object.entries(regions).sort()) {
    const group = document.createElement('optgroup');
    group.label = region;
    names.sort().forEach(n => {
      const opt = document.createElement('option');
      opt.value = n;
      opt.textContent = n;
      group.appendChild(opt);
    });
    bookDestSelect.appendChild(group);
  }
}

// Book a Trip form submission
const bookTripForm = document.getElementById('book-trip-form');
const bookTripSuccess = document.getElementById('book-trip-success');
if (bookTripForm) {
  bookTripForm.addEventListener('submit', (e) => {
    e.preventDefault();
    const data = Object.fromEntries(new FormData(bookTripForm).entries());
    console.log('Trip booking request:', data);
    bookTripForm.style.display = 'none';
    bookTripSuccess.classList.add('show');
  });
}

function openBookPanel() {
  // Close country panel and full-screen pages
  panel.classList.remove('open');
  Object.values(pageOverlays).forEach(p => p.classList.remove('open'));
  if (bookTripForm) {
    bookTripForm.style.display = '';
    bookTripSuccess.classList.remove('show');
    bookTripForm.reset();
  }
  bookPanel.classList.add('open');
  bookPanel.scrollTop = 0;
  dimGlobe(true);
  controls.autoRotate = false;
}

function closeBookPanel() {
  bookPanel.classList.remove('open');
  const anyPageOpen = Object.values(pageOverlays).some(p => p.classList.contains('open'));
  if (!anyPageOpen && !panel.classList.contains('open')) {
    dimGlobe(false);
    controls.autoRotate = true;
  }
}

bookPanelClose.addEventListener('click', closeBookPanel);

function openPage(id) {
  if (id === 'book') { openBookPanel(); return; }
  const overlay = pageOverlays[id];
  if (!overlay) return;
  // Close side panels and other pages
  panel.classList.remove('open');
  bookPanel.classList.remove('open');
  Object.values(pageOverlays).forEach(p => p.classList.remove('open'));
  overlay.classList.add('open');
  overlay.scrollTop = 0;
  dimGlobe(true);
  controls.autoRotate = false;
}

function closeAllPages() {
  Object.values(pageOverlays).forEach(p => p.classList.remove('open'));
  bookPanel.classList.remove('open');
  dimGlobe(false);
  controls.autoRotate = true;
}

// Nav link handlers
document.querySelectorAll('[data-nav]').forEach(link => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    const target = link.dataset.nav;
    openPage(target);
  });
});

// Close buttons on page overlays
document.querySelectorAll('.page-close').forEach(btn => {
  btn.addEventListener('click', closeAllPages);
});

// Escape closes pages and panels
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') {
    if (bookPanel.classList.contains('open')) { closeBookPanel(); return; }
    const anyOpen = Object.values(pageOverlays).some(p => p.classList.contains('open'));
    if (anyOpen) closeAllPages();
  }
});

// Logo click returns to globe
document.querySelector('.nav-brand').addEventListener('click', (e) => {
  e.preventDefault();
  closeAllPages();
  closePanel();
  closeBookingModal();
});

// ─── About Page: Scroll Reveal & CTA ─────────────────────────────────────

const aboutRevealObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
    }
  });
}, { threshold: 0.15 });

function initAboutReveals() {
  document.querySelectorAll('#page-about .about-reveal').forEach(el => {
    el.classList.remove('visible');
    aboutRevealObserver.observe(el);
  });
}

// Re-trigger reveals each time the About page opens
const aboutOverlay = document.getElementById('page-about');
const aboutObserver = new MutationObserver(() => {
  if (aboutOverlay.classList.contains('open')) {
    // Reset and re-observe for fresh animation
    document.querySelectorAll('#page-about .about-reveal').forEach(el => {
      el.classList.remove('visible');
    });
    requestAnimationFrame(() => initAboutReveals());
  }
});
aboutObserver.observe(aboutOverlay, { attributes: true, attributeFilter: ['class'] });

// About CTA button navigates to Book page
const aboutCtaBtn = document.querySelector('.about-cta-btn[data-nav="book"]');
if (aboutCtaBtn) {
  aboutCtaBtn.addEventListener('click', () => {
    closeAllPages();
    openPage('book');
  });
}

// ─── Destinations Page ────────────────────────────────────────────────────

const destGrid = document.getElementById('dest-grid');
const destFilters = document.getElementById('dest-filters');

// Featured countries get double-width cards
const FEATURED_DESTINATIONS = new Set([
  'Japan', 'Italy', 'Iceland', 'Morocco', 'Maldives', 'Australia', 'Peru'
]);

// Display name overrides
const DISPLAY_NAMES = {
  'United States of America': 'United States',
  'United Arab Emirates': 'UAE',
  'Czech Republic': 'Czechia',
};

function getLowestPrice(country) {
  const data = COUNTRIES[country];
  if (!data || !data.offers || !data.offers.length) return null;
  let lowest = Infinity;
  for (const offer of data.offers) {
    const num = parseInt(offer.price.replace(/[^0-9]/g, ''));
    if (!isNaN(num) && num < lowest) lowest = num;
  }
  return lowest === Infinity ? null : lowest;
}

function renderDestGrid(regionFilter) {
  const entries = Object.entries(COUNTRIES)
    .filter(([, data]) => regionFilter === 'all' || data.region === regionFilter);

  // Sort: featured first, then alphabetical
  entries.sort((a, b) => {
    const aFeat = FEATURED_DESTINATIONS.has(a[0]) ? 0 : 1;
    const bFeat = FEATURED_DESTINATIONS.has(b[0]) ? 0 : 1;
    if (aFeat !== bFeat) return aFeat - bFeat;
    return a[0].localeCompare(b[0]);
  });

  destGrid.innerHTML = entries.map(([name, data], i) => {
    const isFeatured = FEATURED_DESTINATIONS.has(name);
    const displayName = DISPLAY_NAMES[name] || name;
    const imgPath = IMAGE_MAP[name] || '';
    const lowestPrice = getLowestPrice(name);
    const priceLabel = lowestPrice ? `From $${lowestPrice.toLocaleString()}` : '';
    const delay = Math.min(i * 0.04, 0.8);

    return `
      <article class="dest-card${isFeatured ? ' featured' : ''}" data-country="${name}" style="animation-delay:${delay}s">
        <div class="dest-card-img" style="background-image:url('${imgPath}')"></div>
        <div class="dest-card-overlay"></div>
        <div class="dest-card-body">
          <span class="dest-card-region">${data.region}</span>
          <h2 class="dest-card-name">${displayName}</h2>
          <span class="dest-card-price">${priceLabel}</span>
          <p class="dest-card-desc">${data.desc}</p>
        </div>
      </article>
    `;
  }).join('');

  // Click handlers — fly to country on globe
  destGrid.querySelectorAll('.dest-card').forEach(card => {
    card.addEventListener('click', () => {
      const name = card.dataset.country;
      closeAllPages();
      flyToCountry(name);
    });
  });
}

// Filter buttons
if (destFilters) {
  destFilters.addEventListener('click', (e) => {
    const btn = e.target.closest('.dest-filter');
    if (!btn) return;
    destFilters.querySelectorAll('.dest-filter').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    renderDestGrid(btn.dataset.region);
  });
}

// Render grid when Destinations page opens
const destOverlay = document.getElementById('page-destinations');
const destPageObserver = new MutationObserver(() => {
  if (destOverlay.classList.contains('open')) {
    // Reset filter to "All"
    destFilters.querySelectorAll('.dest-filter').forEach(b => b.classList.remove('active'));
    destFilters.querySelector('[data-region="all"]').classList.add('active');
    renderDestGrid('all');
  }
});
destPageObserver.observe(destOverlay, { attributes: true, attributeFilter: ['class'] });

// Bottom CTA
const destBottomCta = document.querySelector('.dest-bottom-cta[data-nav="book"]');
if (destBottomCta) {
  destBottomCta.addEventListener('click', () => {
    closeAllPages();
    openPage('book');
  });
}

// ─── Mobile Navigation ───────────────────────────────────────────────────

const mobHamburger = document.getElementById('mob-hamburger');
const mobMenu = document.getElementById('mob-menu');
const mobMenuClose = document.getElementById('mob-menu-close');
const mobBar = document.getElementById('mob-bar');

function openMobMenu() {
  mobMenu.classList.add('open');
}

function closeMobMenu() {
  mobMenu.classList.remove('open');
}

mobHamburger.addEventListener('click', openMobMenu);
mobMenuClose.addEventListener('click', closeMobMenu);

// Mobile menu links
document.querySelectorAll('.mob-menu-link').forEach(link => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    closeMobMenu();
    const target = link.dataset.nav;
    openPage(target);
    updateMobBar(target);
  });
});

// Mobile bottom bar
function updateMobBar(activeNav) {
  mobBar.querySelectorAll('.mob-bar-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.nav === activeNav);
  });
}

mobBar.addEventListener('click', (e) => {
  const btn = e.target.closest('.mob-bar-btn');
  if (!btn) return;
  const target = btn.dataset.nav;

  if (target === 'globe') {
    closeAllPages();
    closePanel();
    closeBookingModal();
  } else {
    openPage(target);
  }
  updateMobBar(target);
});

// Observe page/panel closes to reset bottom bar
const mobBarObserver = new MutationObserver(() => {
  const anyPageOpen = Object.values(pageOverlays).some(p => p.classList.contains('open'));
  const bookOpen = bookPanel.classList.contains('open');
  const countryOpen = panel.classList.contains('open');
  if (!anyPageOpen && !bookOpen && !countryOpen) {
    updateMobBar('globe');
  }
});

// Observe all panels for class changes
[...Object.values(pageOverlays), bookPanel, panel].forEach(el => {
  mobBarObserver.observe(el, { attributes: true, attributeFilter: ['class'] });
});

// ─── Journal ─────────────────────────────────────────────────────────────

const JOURNAL_ARTICLES = [
  {
    id: 'faroe-islands',
    tag: 'Hidden Gem',
    title: 'The Villages of Faroe Islands Nobody Talks About',
    teaser: 'Beyond the postcard cliffs, there are places where the sheep outnumber the tourists a thousand to one.',
    readTime: '5 min read',
    image: 'images/iceland.jpg',
    ctaCountry: 'Iceland',
    body: `
      <p>Everyone knows about Mulafossur waterfall. It's on every Instagram reel, every "places to visit before you die" list. What nobody tells you about the Faroe Islands is what happens when you turn away from the famous spots and start walking.</p>
      <p>The village of Gásadalur had eleven residents when we visited. Eleven. The path down from the ridge was muddy and unmarked, and the wind was doing that sideways thing it does in the North Atlantic — the kind that makes you reconsider every life choice that led you here.</p>
      <p class="article-pullquote">The best places don't announce themselves. They wait for the people stubborn enough to arrive without directions.</p>
      <p>Then you round the corner and there it is: a cluster of grass-roofed houses clinging to the cliff face like they've been arguing with gravity for centuries. Smoke rises from one chimney. A dog sleeps in the path. The ocean crashes below, indifferent to all of it.</p>
      <p>We spent three days in villages like this. Bøsdalafossur, Tjørnuvík, Saksun — each one a painting that hasn't been hung yet. The food was simple: lamb, potatoes, wind-dried fish that tasted like the sea had written a letter. The people were sparse but warm in the way that isolated communities often are — they'd already decided you were worth talking to, because you showed up.</p>
      <p>The Faroe Islands will be famous eventually. That's how it works. But right now, in this window, you can still arrive without a reservation and leave feeling like you discovered something. Not a destination. A feeling.</p>
    `,
  },
  {
    id: 'namibia-dawn',
    tag: 'Destination',
    title: 'Namibia at Dawn: Why We Keep Going Back',
    teaser: 'The desert doesn\'t care about your schedule. At first light, it shows you why.',
    readTime: '6 min read',
    image: 'images/kenya.jpg',
    ctaCountry: 'Kenya',
    body: `
      <p>The alarm goes off at four. Not the gentle kind — the kind set by someone who has done this before and knows that if you miss the light, you miss everything. You pull on layers in the dark, step outside, and the cold hits you like a correction.</p>
      <p>Then the sky starts. It doesn't rise — it blooms. Namibia's dawn is not a sunrise. It's a slow argument between orange and violet that the desert has been having for sixty million years, and you are briefly allowed to witness it.</p>
      <p>We drove Sossusvlei in silence. Not because we agreed to, but because nobody could find a word that would improve on what we were seeing. The dunes — which sound ordinary until you stand at their base and understand they are taller than most buildings you've ever entered — turn from black to rust to gold in the space of twenty minutes.</p>
      <p class="article-pullquote">Some landscapes ask to be photographed. Namibia asks to be remembered. The camera gets about forty percent of it. The rest lives in your chest.</p>
      <p>Deadvlei is what happens when a forest dies and the desert decides to keep the evidence. White clay pan, black trees, orange dunes, blue sky — four colors, arranged by nature with more confidence than any gallery has ever managed. It looks photoshopped in person. That's the strange part. Reality outdoing fiction.</p>
      <p>We keep going back because Namibia is the only place where we've felt genuinely alone on the planet. Not lonely — alone. The good kind. The kind that reminds you the Earth was here before you and will be here after, and in between, it made this for no reason at all.</p>
    `,
  },
  {
    id: 'georgian-wine',
    tag: 'Culture',
    title: 'A Week in Georgian Wine Country, Off Every List',
    teaser: 'Eight thousand years of winemaking, and the rest of the world is only now showing up.',
    readTime: '4 min read',
    image: 'images/croatia.jpg',
    ctaCountry: 'Croatia',
    body: `
      <p>Georgia didn't invent wine. Georgia invented the idea that wine should exist at all. Eight thousand years ago, someone in the Kakheti region buried a clay pot full of crushed grapes and decided to wait. What came out changed civilization. Or at least improved its dinner parties considerably.</p>
      <p>We spent a week in Kakheti, driving between villages that have been making wine the same way since before Rome was a concept. The qvevri method — fermenting in buried clay vessels — is not a technique. It's an inheritance. Families pass down their vessels like other families pass down names.</p>
      <p class="article-pullquote">In Georgia, wine is not a drink. It's a language. The toastmaster speaks it fluently, and by the third glass, so do you.</p>
      <p>The supra — Georgian feast — is where wine becomes something else entirely. A tamada, or toastmaster, guides the table through a series of toasts that start philosophical and end personal. To life. To the land. To the people who aren't here anymore. By the fifth toast, you're crying. By the seventh, you're laughing. By the tenth, you understand why Georgians consider hospitality a competitive sport.</p>
      <p>The food deserves its own dispatch: khinkali dumplings eaten with the hands, khachapuri bread boats with egg and butter that qualify as a religious experience, churchkhela candy that looks like candles and tastes like autumn. But the wine is the thread that pulls it together — amber-colored, slightly tannic, deeply unlike anything you've had before.</p>
    `,
  },
  {
    id: 'albania-coast',
    tag: 'Hidden Gem',
    title: 'The Quiet Coast of Albania: Europe\'s Last Secret',
    teaser: 'While Croatia counts its cruise ships, the Albanian Riviera counts its blessings.',
    readTime: '5 min read',
    image: 'images/montenegro.jpg',
    ctaCountry: 'Montenegro',
    body: `
      <p>There's a stretch of coastline between Vlorë and Sarandë that the travel industry hasn't figured out yet. Give it three years, maybe five. But right now, the Albanian Riviera is what the Amalfi Coast was before someone put it on a poster — stunning, affordable, and blissfully unconcerned with your expectations.</p>
      <p>The water is the first thing. It's the kind of turquoise that makes you check if your sunglasses have a filter. They don't. That's just what happens when limestone meets the Ionian Sea without centuries of commercial development getting in the way.</p>
      <p>Dhermi beach is a crescent of white stone backed by olive groves and a few concrete guesthouses that charge forty euros a night and include breakfast. The breakfast is tomatoes, feta, bread, olives, and coffee strong enough to restructure your personality. It's perfect.</p>
      <p class="article-pullquote">Albania doesn't try to impress you. It just exists, beautifully, and waits for you to notice.</p>
      <p>The road from Llogara Pass to Himara is one of the great drives of Europe — switchbacks dropping from cloud-level pine forests to sea-level fishing villages in twenty minutes. Every bend reveals another bay that would be famous if it were in Italy. But it's in Albania, so it's just there, being gorgeous for the seagulls.</p>
      <p>We met a fisherman in Ksamil who sold us grilled octopus on the dock for six euros. He'd caught it that morning. He was also, it turned out, a retired physics professor. Albania is like that — full of people whose stories are bigger than the country's reputation. The coast is the scenery. The people are the reason to stay.</p>
    `,
  },
];

const journalFeatured = document.getElementById('journal-featured');
const journalMosaic = document.getElementById('journal-mosaic');
const articleView = document.getElementById('article-view');
const articleBack = document.getElementById('article-back');

function renderJournal() {
  const [featured, ...rest] = JOURNAL_ARTICLES;

  // Featured cover story
  journalFeatured.dataset.article = featured.id;
  journalFeatured.innerHTML = `
    <div class="journal-featured-img"><img src="${featured.image}" alt="${featured.title}"></div>
    <div class="journal-featured-overlay"></div>
    <div class="journal-featured-content">
      <span class="journal-featured-tag">${featured.tag}</span>
      <h1 class="journal-featured-title">${featured.title}</h1>
      <p class="journal-featured-teaser">${featured.teaser}</p>
      <span class="journal-featured-meta">${featured.readTime}</span>
      <span class="journal-featured-read">Read the story</span>
    </div>
  `;

  // Mosaic cards
  journalMosaic.innerHTML = rest.map(a => `
    <article class="journal-mcard" data-article="${a.id}">
      <div class="journal-mcard-img">
        <img src="${a.image}" alt="${a.title}" loading="lazy">
        <div class="journal-mcard-overlay"></div>
      </div>
      <div class="journal-mcard-body">
        <span class="journal-mcard-tag">${a.tag}</span>
        <h2 class="journal-mcard-title">${a.title}</h2>
        <p class="journal-mcard-teaser">${a.teaser}</p>
        <span class="journal-mcard-meta">${a.readTime}</span>
      </div>
    </article>
  `).join('');
}

function openArticle(id) {
  const article = JOURNAL_ARTICLES.find(a => a.id === id);
  if (!article) return;

  articleView.innerHTML = `
    <div class="article-hero">
      <img src="${article.image}" alt="${article.title}">
      <div class="article-hero-overlay"></div>
    </div>
    <div class="article-header">
      <span class="article-tag">${article.tag}</span>
      <h1 class="article-title">${article.title}</h1>
      <span class="article-meta">${article.readTime}</span>
    </div>
    <div class="article-body">${article.body}</div>
    <div class="article-cta">
      <span class="article-cta-label">Inspired?</span>
      <button class="article-cta-btn" data-nav="book">Plan a trip here</button>
    </div>
  `;

  // Wire CTA
  articleView.querySelector('.article-cta-btn').addEventListener('click', () => {
    closeAllPages();
    openPage('book');
  });

  openPage('article');
}

// Journal clicks — featured and mosaic
journalFeatured.addEventListener('click', () => {
  openArticle(journalFeatured.dataset.article);
});

journalMosaic.addEventListener('click', (e) => {
  const card = e.target.closest('.journal-mcard');
  if (!card) return;
  openArticle(card.dataset.article);
});

// Article back button returns to journal
articleBack.addEventListener('click', (e) => {
  e.preventDefault();
  e.stopPropagation();
  pageOverlays.article.classList.remove('open');
  pageOverlays.journal.classList.add('open');
});

// Render journal when page opens
const journalOverlay = document.getElementById('page-journal');
const journalObserver = new MutationObserver(() => {
  if (journalOverlay.classList.contains('open')) renderJournal();
});
journalObserver.observe(journalOverlay, { attributes: true, attributeFilter: ['class'] });

// ─── Exit Intent Popup ───────────────────────────────────────────────────

const exitPopup = document.getElementById('exit-popup');
const exitPopupClose = document.getElementById('exit-popup-close');
const exitPopupForm = document.getElementById('exit-popup-form');
let exitShown = sessionStorage.getItem('exitPopupShown') === 'true';

function showExitPopup() {
  if (exitShown) return;
  exitShown = true;
  sessionStorage.setItem('exitPopupShown', 'true');
  exitPopup.classList.add('open');
  exitPopup.setAttribute('aria-hidden', 'false');
}

function closeExitPopup() {
  exitPopup.classList.remove('open');
  exitPopup.setAttribute('aria-hidden', 'true');
}

exitPopupClose.addEventListener('click', closeExitPopup);
exitPopup.querySelector('.exit-popup-backdrop').addEventListener('click', closeExitPopup);
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape' && exitPopup.classList.contains('open')) closeExitPopup();
});

exitPopupForm.addEventListener('submit', (e) => {
  e.preventDefault();
  const email = exitPopupForm.querySelector('input').value;
  console.log('Newsletter signup:', email);
  exitPopup.querySelector('.exit-popup-dialog').innerHTML = `
    <span class="exit-popup-tag">You're in</span>
    <p class="exit-popup-text">First dispatch lands next month.</p>
  `;
  setTimeout(closeExitPopup, 2500);
});

// Trigger on mouse leaving viewport toward top (exit intent)
document.addEventListener('mouseout', (e) => {
  if (e.clientY <= 0 && !exitShown) showExitPopup();
});
