export const COUNTRIES = {
  France: {
    name: 'France',
    region: 'Europe',
    desc: 'The food, the light, the wine. Paris first, then south — lavender fields, limestone villages, a rosé you will remember for years.',
    imagePrompt: 'Landscape photography of lavender fields in Provence, France at golden hour, rows of purple stretching toward a medieval hilltop village, warm light casting long shadows, Canon EOS R5, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'NYC to Paris Nonstop',
        desc: 'Direct flight into Charles de Gaulle, evening departure so you land with the morning.',
        price: '$520',
        per: 'round trip',
        details: ['7h 15m nonstop', 'Evening departure', 'Full meal service'],
      },
      {
        type: 'hotel',
        title: 'Le Marais Boutique Stay',
        desc: 'Fourth-floor walk-up in the Marais, iron balcony, bakery below that opens at six.',
        price: '$185',
        per: 'per night',
        details: ['Central 4th arrondissement', 'King bed, courtyard view', 'Continental breakfast included'],
      },
      {
        type: 'tour',
        title: 'Loire Valley Wine Circuit',
        desc: 'Three chateaux, two cellars, one very long lunch in a converted barn.',
        price: '$290',
        per: 'per person',
        details: ['Full-day guided tour', 'Six wine tastings included', 'Small group, max 10'],
      },
    ],
  },

  Italy: {
    name: 'Italy',
    region: 'Europe',
    desc: 'Every town has a piazza, every piazza has an argument, and every argument ends with espresso. Come hungry, leave slower.',
    imagePrompt: 'Landscape photography of the Amalfi Coast, Italy, colorful cliffside houses cascading toward turquoise Mediterranean water, winding coastal road visible, late afternoon light, shot from a high vantage point, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Direct to Rome Fiumicino',
        desc: 'Overnight flight, land before lunch, gelato by two.',
        price: '$580',
        per: 'round trip',
        details: ['8h 45m nonstop', 'Overnight red-eye option', 'Two free checked bags'],
      },
      {
        type: 'hotel',
        title: 'Trastevere Apartment',
        desc: 'Cobblestone street, terracotta walls, a terrace where you can see three domes.',
        price: '$160',
        per: 'per night',
        details: ['Self-catering kitchen', 'Rooftop terrace access', 'Walking distance to Centro Storico'],
      },
      {
        type: 'tour',
        title: 'Tuscan Hill Town Drive',
        desc: 'Siena, San Gimignano, and a farmhouse lunch with wine the owner made himself.',
        price: '$245',
        per: 'per person',
        details: ['Private driver all day', 'Farm-to-table lunch included', 'Pecorino and olive oil tasting'],
      },
    ],
  },

  Spain: {
    name: 'Spain',
    region: 'Europe',
    desc: 'Dinner at ten, a walk at midnight, sleep when the sun tells you to. The rhythm here rewires you.',
    imagePrompt: 'Landscape photography of La Sagrada Familia in Barcelona at sunset, warm golden light on Gaudi facade, clear sky, tourists small in foreground for scale, architectural detail visible, 28mm wide angle lens',
    offers: [
      {
        type: 'flight',
        title: 'Miami to Barcelona Direct',
        desc: 'Eight hours over the Atlantic, tapas waiting on the other side.',
        price: '$490',
        per: 'round trip',
        details: ['8h 30m nonstop', 'Morning arrival', 'In-flight entertainment'],
      },
      {
        type: 'hotel',
        title: 'Gothic Quarter Hotel',
        desc: 'Stone arches, a courtyard fountain, and Las Ramblas three blocks away.',
        price: '$140',
        per: 'per night',
        details: ['14th-century building', 'Rooftop pool', 'Breakfast buffet included'],
      },
      {
        type: 'tour',
        title: 'San Sebastian Pintxos Crawl',
        desc: 'Seven bars, fourteen small plates, one guide who knows every bartender by name.',
        price: '$120',
        per: 'per person',
        details: ['4-hour evening tour', 'All food and drinks included', 'Max 8 guests'],
      },
    ],
  },

  Portugal: {
    name: 'Portugal',
    region: 'Europe',
    desc: 'Lisbon tilts toward the river. Fado drifts from open doors. The custard tarts cost a euro and taste like they should cost ten.',
    imagePrompt: 'Landscape photography of Lisbon yellow tram 28 climbing a narrow cobblestone hill, pastel-colored buildings with azulejo tiles, laundry hanging between windows, soft morning light, street-level perspective, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Boston to Lisbon Nonstop',
        desc: 'Shortest transatlantic crossing — five and a half hours to Southern Europe.',
        price: '$440',
        per: 'round trip',
        details: ['5h 30m nonstop', 'Red-eye available', 'Priority boarding'],
      },
      {
        type: 'hotel',
        title: 'Alfama Guesthouse',
        desc: 'Tiled floors, iron bed frame, a window seat overlooking the Tagus.',
        price: '$110',
        per: 'per night',
        details: ['Historic Alfama district', 'Daily pastry basket', 'Fado bar downstairs'],
      },
      {
        type: 'tour',
        title: 'Douro Valley Wine Day',
        desc: 'Train along the river, then a boat back, tasting port at three estates.',
        price: '$195',
        per: 'per person',
        details: ['Full day from Porto', 'Lunch at riverside quinta', 'Three port tastings'],
      },
    ],
  },

  Greece: {
    name: 'Greece',
    region: 'Europe',
    desc: 'White walls, blue domes, water so clear you can count the stones at the bottom. The salads alone are worth the flight.',
    imagePrompt: 'Landscape photography of Santorini blue-domed churches overlooking the caldera, white buildings cascading down the cliff, deep blue Aegean Sea, golden hour light, shot from Oia viewpoint, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'Chicago to Athens Direct',
        desc: 'Nonstop seasonal service, land in time for a seaside dinner.',
        price: '$620',
        per: 'round trip',
        details: ['10h 15m nonstop', 'Seasonal May-October', 'Full meal and drinks'],
      },
      {
        type: 'hotel',
        title: 'Santorini Cave Suite',
        desc: 'Carved into the cliff, infinity pool at the edge, caldera view from bed.',
        price: '$320',
        per: 'per night',
        details: ['Private plunge pool', 'Breakfast delivered daily', 'Sunset-facing terrace'],
      },
      {
        type: 'tour',
        title: 'Athens to Delphi Day Trip',
        desc: 'Oracle of Delphi, mountain monastery, lunch in a village where the waiter remembers you.',
        price: '$135',
        per: 'per person',
        details: ['Full day with transport', 'Licensed archaeologist guide', 'Lunch in Arachova village'],
      },
    ],
  },

  Switzerland: {
    name: 'Switzerland',
    region: 'Europe',
    desc: 'Trains through mountains that look painted. Cheese that costs as much as a steak, and is worth it. Everything runs on time, including the cows.',
    imagePrompt: 'Landscape photography of the Matterhorn reflected in Riffelsee lake, Swiss Alps, snow-capped peak, wildflower meadow in foreground, crystal clear water, early morning light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'JFK to Zurich Nonstop',
        desc: 'Direct into Zurich, train connections to anywhere in the country within hours.',
        price: '$680',
        per: 'round trip',
        details: ['8h nonstop', 'Swiss Air service', 'Free rail pass add-on available'],
      },
      {
        type: 'hotel',
        title: 'Interlaken Alpine Lodge',
        desc: 'Wood-paneled room, two lakes visible from the balcony, mountains filling every window.',
        price: '$230',
        per: 'per night',
        details: ['Between Lake Thun and Brienz', 'Half-board option', 'Jungfrau railway access'],
      },
      {
        type: 'tour',
        title: 'Glacier Express Day Pass',
        desc: 'Eight hours through 291 bridges and 91 tunnels — the slowest express train on earth.',
        price: '$340',
        per: 'per person',
        details: ['Zermatt to St. Moritz', 'Panoramic windows', 'Three-course lunch on board'],
      },
    ],
  },

  Croatia: {
    name: 'Croatia',
    region: 'Europe',
    desc: 'Dubrovnik walls the color of honey. Islands you reach by ferries that smell like diesel and salt. The coast is still half-secret.',
    imagePrompt: 'Landscape photography of Dubrovnik old town from above, orange terracotta rooftops, medieval walls meeting the Adriatic Sea, crystal blue water, sailboats in harbor, late afternoon golden light, 28mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Philadelphia to Dubrovnik',
        desc: 'One connection in Frankfurt, arrive by midday Mediterranean time.',
        price: '$590',
        per: 'round trip',
        details: ['One-stop via Frankfurt', 'Total travel 12h', 'Checked bag included'],
      },
      {
        type: 'hotel',
        title: 'Old Town Stone House',
        desc: 'Sixteenth-century walls, modern shower, a roof terrace where you eat figs and stare at the sea.',
        price: '$175',
        per: 'per night',
        details: ['Inside city walls', 'Air conditioning', 'Private terrace'],
      },
      {
        type: 'tour',
        title: 'Elaphiti Islands Sail',
        desc: 'Three islands by sailboat, swimming stops in coves no road can reach.',
        price: '$110',
        per: 'per person',
        details: ['Full-day sailing trip', 'Lunch and wine on board', 'Snorkeling gear provided'],
      },
    ],
  },

  Iceland: {
    name: 'Iceland',
    region: 'Europe',
    desc: 'Geysers, black sand, hot rivers in the middle of nowhere. The light in June never leaves. The silence is enormous.',
    imagePrompt: 'Landscape photography of Skogafoss waterfall in Iceland, massive cascade falling over black basalt cliff, green moss-covered hillside, rainbow in the mist, overcast dramatic sky, 24mm ultra-wide lens',
    offers: [
      {
        type: 'flight',
        title: 'Boston to Reykjavik',
        desc: 'Five hours and you are standing on a different tectonic plate.',
        price: '$380',
        per: 'round trip',
        details: ['5h 10m nonstop', 'Icelandair service', 'Year-round daily flights'],
      },
      {
        type: 'hotel',
        title: 'Vik Guesthouse',
        desc: 'Wood cabin on the south coast, black beach walking distance, northern lights from your window in winter.',
        price: '$195',
        per: 'per night',
        details: ['South coast location', 'Hot tub on-site', 'Breakfast included'],
      },
      {
        type: 'tour',
        title: 'Golden Circle and Snorkel',
        desc: 'Geysir, Gullfoss, Thingvellir — then snorkeling between continents in water so clear it feels fake.',
        price: '$280',
        per: 'per person',
        details: ['10-hour guided tour', 'Dry suit and gear included', 'Hotel pickup from Reykjavik'],
      },
    ],
  },

  Norway: {
    name: 'Norway',
    region: 'Europe',
    desc: 'Fjords that drop a thousand meters straight down. Fishing villages painted red. It costs a fortune and every krone is earned.',
    imagePrompt: 'Landscape photography of Geirangerfjord Norway, steep green mountains plunging into deep blue fjord water, tiny cruise ship for scale, waterfalls cascading down cliffs, summer light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Newark to Oslo Direct',
        desc: 'Nonstop overnight, land in Scandinavia before breakfast.',
        price: '$560',
        per: 'round trip',
        details: ['7h 40m nonstop', 'SAS or United', 'Evening departure'],
      },
      {
        type: 'hotel',
        title: 'Bergen Harbor Hotel',
        desc: 'Wooden wharf building, fish market next door, rain is part of the deal.',
        price: '$210',
        per: 'per night',
        details: ['Bryggen waterfront', 'Fjord-view rooms available', 'Breakfast buffet included'],
      },
      {
        type: 'tour',
        title: 'Norway in a Nutshell',
        desc: 'Train, boat, bus through the fjords — the most scenic commute on earth, condensed into one day.',
        price: '$310',
        per: 'per person',
        details: ['Bergen to Oslo or reverse', 'Flam Railway included', 'Fjord cruise included'],
      },
    ],
  },

  Ireland: {
    name: 'Ireland',
    region: 'Europe',
    desc: 'Forty shades of green is not a cliché when you are standing in them. The pubs close late. The stories go longer.',
    imagePrompt: 'Landscape photography of Cliffs of Moher Ireland, dramatic sea cliffs dropping into Atlantic Ocean, green grass on top, waves crashing below, moody overcast sky with light breaking through, 28mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'JFK to Dublin Nonstop',
        desc: 'Six hours and change — shorter than driving to Montreal.',
        price: '$420',
        per: 'round trip',
        details: ['6h 20m nonstop', 'Aer Lingus or Delta', 'US preclearance in Dublin'],
      },
      {
        type: 'hotel',
        title: 'Temple Bar Inn',
        desc: 'Central Dublin, river-facing room, trad session downstairs most nights.',
        price: '$155',
        per: 'per night',
        details: ['Temple Bar location', 'Irish breakfast included', 'Pub on ground floor'],
      },
      {
        type: 'tour',
        title: 'Wild Atlantic Way Weekend',
        desc: 'Cliffs of Moher, Burren limestone, Galway oysters, and a driver who will not stop talking — in the best way.',
        price: '$385',
        per: 'per person',
        details: ['2-day tour from Dublin', 'One night in Galway', 'All transport and entry fees'],
      },
    ],
  },

  'Czech Republic': {
    name: 'Czech Republic',
    region: 'Europe',
    desc: 'Prague after dark, bridge towers lit gold, beer cheaper than water and twice as good. The architecture alone takes a week.',
    imagePrompt: 'Landscape photography of Charles Bridge Prague at dawn, Gothic bridge towers, statues silhouetted against pastel sky, Vltava River reflecting city lights, Prague Castle in background, mist on the water, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'DC to Prague via Frankfurt',
        desc: 'One quick connection, arrive in Bohemia by afternoon.',
        price: '$510',
        per: 'round trip',
        details: ['One-stop via Frankfurt', 'Total 10h 30m', 'Lufthansa connection'],
      },
      {
        type: 'hotel',
        title: 'Old Town Square Pension',
        desc: 'Astronomical clock visible from your window, wooden beams, a courtyard with morning coffee.',
        price: '$95',
        per: 'per night',
        details: ['Steps from Old Town Square', 'Vaulted ceilings', 'Breakfast included'],
      },
      {
        type: 'tour',
        title: 'Bohemian Brewery Trail',
        desc: 'Three historic breweries, a medieval cellar, and a beer you cannot buy outside the country.',
        price: '$85',
        per: 'per person',
        details: ['Half-day afternoon tour', 'Five beer tastings', 'Traditional Czech snacks'],
      },
    ],
  },

  Turkey: {
    name: 'Turkey',
    region: 'Europe',
    desc: 'Istanbul straddles two continents and about ten centuries. Hot air balloons over Cappadocia at dawn. Tea in tulip glasses, always.',
    imagePrompt: 'Landscape photography of Cappadocia Turkey at sunrise, dozens of hot air balloons floating over fairy chimney rock formations, warm golden light, valleys and cave dwellings below, shot from a hilltop, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Chicago to Istanbul Direct',
        desc: 'Turkish Airlines nonstop, land at their massive new hub.',
        price: '$610',
        per: 'round trip',
        details: ['11h nonstop', 'Turkish Airlines', 'Lounge access with business'],
      },
      {
        type: 'hotel',
        title: 'Sultanahmet Heritage Hotel',
        desc: 'Ottoman townhouse, Blue Mosque from the rooftop, call to prayer as your alarm clock.',
        price: '$120',
        per: 'per night',
        details: ['Historic Sultanahmet district', 'Rooftop breakfast terrace', 'Hamam next door'],
      },
      {
        type: 'tour',
        title: 'Cappadocia Balloon and Cave',
        desc: 'Sunrise balloon flight, underground city, dinner in a cave restaurant carved from volcanic rock.',
        price: '$350',
        per: 'per person',
        details: ['2-day tour from Istanbul', 'Domestic flights included', 'Cave hotel one night'],
      },
    ],
  },

  Germany: {
    name: 'Germany',
    region: 'Europe',
    desc: 'Beer gardens under chestnut trees, castles that look invented, Christmas markets that smell like cinnamon and mulled wine. The autobahn is real and it is fast.',
    imagePrompt: 'Landscape photography of Neuschwanstein Castle in Bavaria, fairytale castle perched on a forested hillside, Alps in background, autumn foliage in gold and orange, misty morning light, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'JFK to Munich Nonstop',
        desc: 'Direct into Bavaria, gateway to castles, Alps, and the best pretzels on earth.',
        price: '$540',
        per: 'round trip',
        details: ['8h 30m nonstop', 'Lufthansa service', 'Evening departure'],
      },
      {
        type: 'hotel',
        title: 'Berlin Mitte Boutique',
        desc: 'Former gallery space turned hotel, exposed brick, courtyard garden, Friedrichstraße on foot.',
        price: '$165',
        per: 'per night',
        details: ['Central Mitte district', 'King bed, rainfall shower', 'Breakfast buffet included'],
      },
      {
        type: 'tour',
        title: 'Rhine Valley Wine Cruise',
        desc: 'Half-day river cruise past hilltop castles and terraced vineyards. Three wines, one very good lunch.',
        price: '$195',
        per: 'per person',
        details: ['4-hour river cruise', 'Three wine tastings', 'Castle commentary on board'],
      },
    ],
  },

  'United Kingdom': {
    name: 'United Kingdom',
    region: 'Europe',
    desc: 'Pubs with low ceilings and real ales. London moves at five speeds at once. The countryside is so green it looks filtered.',
    imagePrompt: 'Landscape photography of Tower Bridge London at blue hour, illuminated bridge spanning the Thames, city lights reflecting on the water, St Pauls dome in background, moody clouds, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'LAX to London Heathrow',
        desc: 'Nonstop into the capital, Heathrow Express to Paddington in fifteen minutes.',
        price: '$580',
        per: 'round trip',
        details: ['10h 30m nonstop', 'Multiple daily departures', 'Full meal service'],
      },
      {
        type: 'hotel',
        title: 'Covent Garden Townhouse',
        desc: 'Georgian townhouse, velvet headboards, a cocktail bar downstairs that takes its gin seriously.',
        price: '$245',
        per: 'per night',
        details: ['West End location', 'Complimentary afternoon tea', 'Access to private garden'],
      },
      {
        type: 'tour',
        title: 'Cotswolds Day Trip',
        desc: 'Honey-stone villages, rolling hills, a pub lunch in a place that has not changed since the 1600s.',
        price: '$165',
        per: 'per person',
        details: ['Full day from London', 'Three village stops', 'Pub lunch included'],
      },
    ],
  },

  Netherlands: {
    name: 'Netherlands',
    region: 'Europe',
    desc: 'Canals, bicycles, and a directness that is refreshing. Tulip fields in spring that look like someone spilled paint. Stroopwafels warm off the press.',
    imagePrompt: 'Landscape photography of Amsterdam canal houses at twilight, tall narrow brick buildings with gabled facades reflected in still canal water, bicycles on bridge, warm window light, 28mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'Atlanta to Amsterdam',
        desc: 'Nonstop into Schiphol, one of the best-connected airports in Europe.',
        price: '$510',
        per: 'round trip',
        details: ['8h 45m nonstop', 'KLM or Delta', 'Daytime departure option'],
      },
      {
        type: 'hotel',
        title: 'Jordaan Canal House',
        desc: 'Seventeenth-century canal house, steep Dutch stairs, roof terrace overlooking the Prinsengracht.',
        price: '$210',
        per: 'per night',
        details: ['Jordaan neighborhood', 'Canal-view rooms', 'Dutch breakfast included'],
      },
      {
        type: 'tour',
        title: 'Keukenhof & Windmill Tour',
        desc: 'Seven million tulips, historic windmills, a cheese farm where you leave with more cheese than planned.',
        price: '$125',
        per: 'per person',
        details: ['Spring season only', 'Skip-the-line Keukenhof', 'Cheese tasting included'],
      },
    ],
  },

  Austria: {
    name: 'Austria',
    region: 'Europe',
    desc: 'Vienna is a city that dresses for dinner. Salzburg sounds like Mozart, literally. The Alps start in the backyard and they do not stop.',
    imagePrompt: 'Landscape photography of Hallstatt village in Austria, pastel lakeside houses reflected in mirror-like lake, dramatic alpine mountains rising behind, morning mist, church spire, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Chicago to Vienna Direct',
        desc: 'Nonstop into the heart of Central Europe, waltz your way through customs.',
        price: '$620',
        per: 'round trip',
        details: ['9h 20m nonstop', 'Austrian Airlines', 'Evening departure'],
      },
      {
        type: 'hotel',
        title: 'Vienna Ringstraße Suite',
        desc: 'High ceilings, parquet floors, a Sachertorte waiting at check-in. Opera house two blocks away.',
        price: '$195',
        per: 'per night',
        details: ['First district location', 'Breakfast salon', 'Concierge service'],
      },
      {
        type: 'tour',
        title: 'Sound of Music Salzburg',
        desc: 'Mirabell Gardens, Mondsee church, the gazebo — you will sing whether you want to or not.',
        price: '$145',
        per: 'per person',
        details: ['Full day from Vienna', 'High-speed train included', 'Licensed guide'],
      },
    ],
  },

  Sweden: {
    name: 'Sweden',
    region: 'Europe',
    desc: 'Design so clean it hurts. Fika is not a break, it is a philosophy. Midnight sun in summer, northern lights in winter. Pick your impossible sky.',
    imagePrompt: 'Landscape photography of Stockholm Gamla Stan old town at sunset, colorful medieval buildings along the waterfront, church spires, calm Baltic water reflecting warm light, boats moored along the quay, 28mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Newark to Stockholm',
        desc: 'Nonstop into Arlanda, train to the city center in twenty minutes flat.',
        price: '$560',
        per: 'round trip',
        details: ['8h nonstop', 'SAS service', 'Morning arrival'],
      },
      {
        type: 'hotel',
        title: 'Södermalm Design Hotel',
        desc: 'Scandinavian minimalism done right. Blond wood, linen sheets, coffee that takes itself very seriously.',
        price: '$200',
        per: 'per night',
        details: ['Trendy Södermalm district', 'Sauna access', 'Organic breakfast'],
      },
      {
        type: 'tour',
        title: 'Stockholm Archipelago Cruise',
        desc: 'Twenty-four thousand islands. A red wooden cottage on every one. Silence you can hear.',
        price: '$175',
        per: 'per person',
        details: ['Full-day island hopping', 'Seafood lunch on-island', 'Small group, max 12'],
      },
    ],
  },

  Denmark: {
    name: 'Denmark',
    region: 'Europe',
    desc: 'Hygge is real and it is everywhere — candles, blankets, pastries the size of your head. Copenhagen is the city that bikes designed.',
    imagePrompt: 'Landscape photography of Nyhavn Copenhagen, colorful 17th-century townhouses along the canal, sailboats moored in foreground, bright clear sky, cafe terraces with people, warm summer afternoon light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'SFO to Copenhagen',
        desc: 'One stop, quick connection in Reykjavik or London. Arrive for a late Danish lunch.',
        price: '$590',
        per: 'round trip',
        details: ['Total 11h via Reykjavik', 'Icelandair or SAS', 'Checked bag included'],
      },
      {
        type: 'hotel',
        title: 'Vesterbro Townhouse',
        desc: 'Converted townhouse, design furniture you can actually buy, the meatpacking district at your door.',
        price: '$185',
        per: 'per night',
        details: ['Vesterbro neighborhood', 'Bike rental included', 'Organic Danish breakfast'],
      },
      {
        type: 'tour',
        title: 'New Nordic Food Walk',
        desc: 'Six stops, four hours, one philosophy: local, seasonal, and better than it has any right to be.',
        price: '$135',
        per: 'per person',
        details: ['4-hour guided food tour', 'Six tastings and two drinks', 'Small group, max 10'],
      },
    ],
  },

  Poland: {
    name: 'Poland',
    region: 'Europe',
    desc: 'Kraków at night looks like a painting someone left the lights on in. Pierogi are a complete food group. History on every corner, beauty on every other.',
    imagePrompt: 'Landscape photography of Kraków Main Market Square at blue hour, St Marys Basilica illuminated, historic cloth hall, cafe lights glowing, cobblestone square, dramatic sky, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'JFK to Kraków',
        desc: 'One stop through Warsaw or Frankfurt. Land in the most beautiful square in Central Europe.',
        price: '$480',
        per: 'round trip',
        details: ['Total 10h one-stop', 'LOT Polish Airlines', 'Checked bag included'],
      },
      {
        type: 'hotel',
        title: 'Old Town Apartment',
        desc: 'Vaulted brick ceilings, wooden floors that creak in the right way, the square outside your window.',
        price: '$95',
        per: 'per night',
        details: ['Old Town location', 'Full kitchen', 'Self check-in'],
      },
      {
        type: 'tour',
        title: 'Wieliczka Salt Mine',
        desc: 'Underground cathedral carved from salt, chandeliers made of salt, a lake that tastes of — yes, salt.',
        price: '$75',
        per: 'per person',
        details: ['Half-day guided tour', 'Hotel pickup included', 'Underground 135m deep'],
      },
    ],
  },

  Hungary: {
    name: 'Hungary',
    region: 'Europe',
    desc: 'Budapest is two cities split by a river and joined by bridges that glow at night. Thermal baths, ruin bars, goulash that fixes everything.',
    imagePrompt: 'Landscape photography of Hungarian Parliament Building in Budapest at blue hour, illuminated Gothic Revival architecture reflected in the Danube River, Chain Bridge in foreground, warm city lights, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Philadelphia to Budapest',
        desc: 'One stop via Frankfurt or Vienna. Arrive in time for a thermal bath before dinner.',
        price: '$520',
        per: 'round trip',
        details: ['Total 11h one-stop', 'Lufthansa or Austrian', 'Checked bag included'],
      },
      {
        type: 'hotel',
        title: 'District VII Ruin Bar Hotel',
        desc: 'Boutique hotel in the Jewish Quarter, exposed brick, rooftop bar, ruin pubs on your doorstep.',
        price: '$110',
        per: 'per night',
        details: ['Jewish Quarter location', 'Rooftop terrace', 'Breakfast included'],
      },
      {
        type: 'tour',
        title: 'Danube Evening Cruise',
        desc: 'Parliament, Chain Bridge, Buda Castle — all lit up, all reflected, all from a glass of Hungarian wine.',
        price: '$85',
        per: 'per person',
        details: ['2-hour evening cruise', 'Welcome drink and wine', 'Live piano on board'],
      },
    ],
  },

  Belgium: {
    name: 'Belgium',
    region: 'Europe',
    desc: 'Chocolate, beer, waffles — the holy trinity. Bruges looks like it was built for a film set. Brussels argues about politics in three languages.',
    imagePrompt: 'Landscape photography of Grand Place Brussels at night, ornate Baroque guild halls illuminated with golden light, cobblestone square reflecting after rain, Town Hall spire, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'DC to Brussels Nonstop',
        desc: 'Direct into the heart of Europe, fast trains to anywhere from here.',
        price: '$490',
        per: 'round trip',
        details: ['8h nonstop', 'United or Brussels Airlines', 'Evening departure'],
      },
      {
        type: 'hotel',
        title: 'Bruges Canal Room',
        desc: 'Medieval townhouse, canal out the window, complimentary chocolate at turndown. Obviously.',
        price: '$175',
        per: 'per night',
        details: ['Historic center location', 'Canal view', 'Belgian breakfast included'],
      },
      {
        type: 'tour',
        title: 'Belgian Beer & Chocolate Trail',
        desc: 'Three breweries, two chocolatiers, one waffle stop. You will need a longer belt.',
        price: '$120',
        per: 'per person',
        details: ['Full day Brussels and Bruges', 'Six beer tastings', 'Chocolate workshop included'],
      },
    ],
  },

  Finland: {
    name: 'Finland',
    region: 'Europe',
    desc: 'Saunas outnumber cars. Lapland has reindeer and silence and a sky that turns green when no one is watching. Helsinki is quiet confidence in concrete and wood.',
    imagePrompt: 'Landscape photography of northern lights aurora borealis over a frozen Finnish Lapland lake, green and purple curtains of light reflected in ice, snow-covered pine trees, glass igloo hotel visible, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'NYC to Helsinki',
        desc: 'Nonstop into the cleanest airport you have ever seen. Sauna awaits.',
        price: '$580',
        per: 'round trip',
        details: ['8h 30m nonstop', 'Finnair service', 'Northern route'],
      },
      {
        type: 'hotel',
        title: 'Glass Igloo Lapland',
        desc: 'Sleep under the northern lights without getting cold. Heated glass roof, private sauna, reindeer outside.',
        price: '$380',
        per: 'per night',
        details: ['Arctic Circle location', 'Glass-roofed cabin', 'Northern lights wake-up call'],
      },
      {
        type: 'tour',
        title: 'Husky Safari & Ice Fishing',
        desc: 'Six huskies, a sled, frozen lakes, and a campfire lunch in the middle of nowhere.',
        price: '$220',
        per: 'per person',
        details: ['Full day in Lapland', 'Thermal gear provided', 'Campfire lunch included'],
      },
    ],
  },

  Montenegro: {
    name: 'Montenegro',
    region: 'Europe',
    desc: 'The Bay of Kotor looks like a Norwegian fjord that moved to the Mediterranean. Tiny, stunning, and still half-secret.',
    imagePrompt: 'Landscape photography of Bay of Kotor Montenegro from above, deep blue fjord-like bay surrounded by dramatic mountains, red-roofed old town of Kotor below, cruise ship for scale, afternoon light, 28mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'London to Tivat',
        desc: 'Short hop to the Adriatic, taxi to Kotor in twenty minutes. The water is already turquoise.',
        price: '$320',
        per: 'round trip',
        details: ['2h 45m direct', 'Seasonal service', 'Carry-on included'],
      },
      {
        type: 'hotel',
        title: 'Kotor Old Town Stone House',
        desc: 'Medieval stone walls, modern plumbing, a roof terrace where the bay fills the entire view.',
        price: '$130',
        per: 'per night',
        details: ['Inside city walls', 'Sea-view terrace', 'Air conditioning'],
      },
      {
        type: 'tour',
        title: 'Bay of Kotor Boat Tour',
        desc: 'Island churches, blue caves, swimming stops in water so clear you can see your shadow on the seabed.',
        price: '$90',
        per: 'per person',
        details: ['Full-day boat trip', 'Lunch and drinks on board', 'Snorkeling gear provided'],
      },
    ],
  },

  Slovenia: {
    name: 'Slovenia',
    region: 'Europe',
    desc: 'Lake Bled with that church on the island — yes, it is real. Ljubljana is the smallest capital that feels like it has everything. Two million people, zero pretension.',
    imagePrompt: 'Landscape photography of Lake Bled Slovenia, emerald green lake with island church and bell tower, medieval castle on cliff above, Julian Alps snow-capped in background, morning mist, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Munich to Ljubljana',
        desc: 'Quick connection through Munich, or drive the Alpine pass and arrive speechless.',
        price: '$380',
        per: 'round trip',
        details: ['Total 5h one-stop', 'Via Munich or Vienna', 'Checked bag included'],
      },
      {
        type: 'hotel',
        title: 'Lake Bled Villa',
        desc: 'Lakefront villa, balcony over the water, the island church lit up at night like a secret.',
        price: '$155',
        per: 'per night',
        details: ['Lakeside location', 'Balcony with lake view', 'Cream cake at check-in'],
      },
      {
        type: 'tour',
        title: 'Vintgar Gorge & Bled Island',
        desc: 'Wooden walkways over turquoise rapids, then a rowboat to the island. Ring the bell, make a wish.',
        price: '$95',
        per: 'per person',
        details: ['Half-day guided tour', 'Traditional pletna boat ride', 'Bled cream cake included'],
      },
    ],
  },

  Japan: {
    name: 'Japan',
    region: 'Asia',
    desc: 'Temples older than most countries. Trains that run to the second. A convenience store onigiri at midnight that has no business being that good.',
    imagePrompt: 'Landscape photography of Fushimi Inari shrine in Kyoto, thousands of vermillion torii gates forming a tunnel up the hillside, dappled light filtering through, single figure walking in distance, 35mm lens, morning light',
    offers: [
      {
        type: 'flight',
        title: 'LAX to Tokyo Narita',
        desc: 'Direct across the Pacific, land in time for a ramen dinner.',
        price: '$750',
        per: 'round trip',
        details: ['11h 30m nonstop', 'ANA or JAL', 'Two meals served'],
      },
      {
        type: 'hotel',
        title: 'Shinjuku Business Hotel',
        desc: 'Small room, immaculate bed, a vending machine hallway, and the entire city outside the door.',
        price: '$130',
        per: 'per night',
        details: ['Central Shinjuku location', 'Onsen bath on top floor', 'Pocket WiFi included'],
      },
      {
        type: 'tour',
        title: 'Kyoto Temple Circuit',
        desc: 'Five temples, a bamboo grove, a tea ceremony in a room with no right angles by accident.',
        price: '$165',
        per: 'per person',
        details: ['Full-day guided walk', 'Tea ceremony included', 'Max 6 guests'],
      },
    ],
  },

  Thailand: {
    name: 'Thailand',
    region: 'Asia',
    desc: 'Street food that makes restaurant food jealous. Islands in the south, temples in the north, chaos in Bangkok that somehow works.',
    imagePrompt: 'Landscape photography of Wat Arun temple in Bangkok at sunset, ornate spires reflecting on the Chao Phraya River, long-tail boats in foreground, warm orange and purple sky, 28mm wide angle lens',
    offers: [
      {
        type: 'flight',
        title: 'San Francisco to Bangkok',
        desc: 'One stop in Tokyo or Seoul, worth every hour for what waits on the other end.',
        price: '$680',
        per: 'round trip',
        details: ['One-stop via Tokyo', 'Total 18h', 'Full meal service'],
      },
      {
        type: 'hotel',
        title: 'Chiang Mai Teak Villa',
        desc: 'Teak house in a garden, pool under frangipani trees, night market a short walk away.',
        price: '$65',
        per: 'per night',
        details: ['Old City location', 'Garden pool', 'Scooter rental available'],
      },
      {
        type: 'tour',
        title: 'Khao Sok Lake Float',
        desc: 'Floating bungalow on a jungle lake, limestone karsts all around, gibbons as neighbors.',
        price: '$180',
        per: 'per person',
        details: ['2-day jungle experience', 'All meals included', 'Kayak and night safari'],
      },
    ],
  },

  Vietnam: {
    name: 'Vietnam',
    region: 'Asia',
    desc: 'Pho at five in the morning, motorbikes in every direction, limestone towers rising from green water. The coffee alone is a reason to go.',
    imagePrompt: 'Landscape photography of Ha Long Bay Vietnam, emerald green water dotted with thousands of limestone karst islands, traditional junk boat with red sails, misty atmosphere, aerial perspective, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'LA to Hanoi via Seoul',
        desc: 'Quick connection through Incheon, arrive in the Old Quarter by evening.',
        price: '$620',
        per: 'round trip',
        details: ['One-stop via Seoul', 'Total 17h', 'Korean Air connection'],
      },
      {
        type: 'hotel',
        title: 'Hoi An Riverside Room',
        desc: 'Lantern-lit street, tailor shops on every corner, a balcony over the Thu Bon River.',
        price: '$55',
        per: 'per night',
        details: ['Old Town riverside', 'Bicycle included', 'Breakfast and laundry'],
      },
      {
        type: 'tour',
        title: 'Ha Long Bay Overnight Junk',
        desc: 'Wooden junk boat through the karsts, kayaking into caves, sleeping on the water.',
        price: '$210',
        per: 'per person',
        details: ['2 days, 1 night on board', 'All meals and kayaking', 'Tai chi at sunrise'],
      },
    ],
  },

  Indonesia: {
    name: 'Indonesia',
    region: 'Asia',
    desc: 'Seventeen thousand islands. Rice terraces cut like staircases into mountains. Bali gets the press, but Flores and Sulawesi keep the secrets.',
    imagePrompt: 'Landscape photography of Tegallalang rice terraces in Bali, lush green carved terraces descending into a valley, coconut palms, morning mist, warm tropical light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Tokyo to Bali via Jakarta',
        desc: 'Short hop through Jakarta, touch down in Denpasar with frangipani-scented air.',
        price: '$550',
        per: 'round trip',
        details: ['One-stop via Jakarta', 'Total 10h', 'Garuda Indonesia'],
      },
      {
        type: 'hotel',
        title: 'Ubud Jungle Lodge',
        desc: 'Open-air bathroom, infinity pool over the ravine, monkeys in the trees — not always welcome.',
        price: '$90',
        per: 'per night',
        details: ['Jungle valley setting', 'Yoga classes included', 'Organic breakfast daily'],
      },
      {
        type: 'tour',
        title: 'Komodo Island Expedition',
        desc: 'Two days by boat, dragons on the beach, manta rays underneath you, pink sand between your toes.',
        price: '$320',
        per: 'per person',
        details: ['2-day live-aboard boat', 'Snorkeling gear included', 'National park fees covered'],
      },
    ],
  },

  India: {
    name: 'India',
    region: 'Asia',
    desc: 'A billion people and not a dull meal among them. The Taj at dawn. Varanasi at dusk. Everything in between is louder and more beautiful than you expect.',
    imagePrompt: 'Landscape photography of Taj Mahal at sunrise from across the Yamuna River, white marble dome reflected in still water, warm orange sky, birds flying overhead, atmospheric haze, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Newark to Delhi Nonstop',
        desc: 'Direct flight on Air India, land in time for a thali dinner.',
        price: '$650',
        per: 'round trip',
        details: ['14h 30m nonstop', 'Air India direct', 'Two meals and snacks'],
      },
      {
        type: 'hotel',
        title: 'Jaipur Haveli Stay',
        desc: 'Sandstone courtyard house, hand-blocked textiles on the walls, chai brought to your room at seven.',
        price: '$75',
        per: 'per night',
        details: ['Pink City old quarter', 'Rooftop dining', 'Heritage property'],
      },
      {
        type: 'tour',
        title: 'Rajasthan Golden Triangle',
        desc: 'Delhi, Agra, Jaipur — forts, tombs, and markets where the bargaining is half the fun.',
        price: '$480',
        per: 'per person',
        details: ['5-day guided circuit', 'All hotels and transport', 'Taj Mahal sunrise visit'],
      },
    ],
  },

  'South Korea': {
    name: 'South Korea',
    region: 'Asia',
    desc: 'Seoul moves at fiber-optic speed. Temples sit in forests twenty minutes from skyscrapers. The fried chicken deserves its own guidebook.',
    imagePrompt: 'Landscape photography of Gyeongbokgung Palace in Seoul with modern skyline behind, traditional Korean architecture with curved rooflines, cherry blossoms in foreground, spring light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'SFO to Seoul Incheon',
        desc: 'Nonstop on Korean Air, arrive at the best-designed airport in the world.',
        price: '$690',
        per: 'round trip',
        details: ['11h 15m nonstop', 'Korean Air', 'Bibimbap on board'],
      },
      {
        type: 'hotel',
        title: 'Bukchon Hanok Stay',
        desc: 'Traditional wooden house with heated floors, paper sliding doors, palace views at dawn.',
        price: '$110',
        per: 'per night',
        details: ['Historic Bukchon village', 'Ondol heated floors', 'Korean breakfast available'],
      },
      {
        type: 'tour',
        title: 'DMZ and JSA Tour',
        desc: 'Stand on the most militarized border on earth. Peer into North Korea. Process it over Korean BBQ after.',
        price: '$95',
        per: 'per person',
        details: ['Full-day from Seoul', 'JSA conference room visit', 'Passport required'],
      },
    ],
  },

  'Sri Lanka': {
    name: 'Sri Lanka',
    region: 'Asia',
    desc: 'Tea plantations in the highlands, elephants in the lowlands, surf on both coasts. An island the size of Ireland with ten times the variety.',
    imagePrompt: 'Landscape photography of Sigiriya Lion Rock fortress in Sri Lanka, massive rock formation rising above lush green jungle canopy, ancient ruins visible on top, dramatic clouds, golden hour light, 28mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'London to Colombo Direct',
        desc: 'Overnight to Sri Lanka, wake up in the tropics.',
        price: '$580',
        per: 'round trip',
        details: ['10h 45m nonstop', 'SriLankan Airlines', 'Night flight available'],
      },
      {
        type: 'hotel',
        title: 'Ella Mountain Bungalow',
        desc: 'Colonial-era tea bungalow, cloud forest on three sides, Nine Arches Bridge visible from the garden.',
        price: '$70',
        per: 'per night',
        details: ['Hill country Ella town', 'Tea plantation tours', 'Home-cooked Sri Lankan meals'],
      },
      {
        type: 'tour',
        title: 'Southern Coast Safari and Surf',
        desc: 'Yala leopards in the morning, Mirissa waves in the afternoon, seafood at a beach shack by dark.',
        price: '$260',
        per: 'per person',
        details: ['3-day south coast loop', 'Safari jeep and board rental', 'Beachfront accommodation'],
      },
    ],
  },

  Nepal: {
    name: 'Nepal',
    region: 'Asia',
    desc: 'Eight of the ten tallest mountains on earth. Prayer flags snapping in thin air. Kathmandu is chaos; the trails above it are the opposite.',
    imagePrompt: 'Landscape photography of Annapurna mountain range from Poon Hill at sunrise, snow-capped Himalayan peaks glowing orange and pink, prayer flags in foreground, cloud sea below, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Delhi to Kathmandu',
        desc: 'Ninety-minute hop over the Gangetic Plain, Himalayas filling the window on approach.',
        price: '$220',
        per: 'round trip',
        details: ['1h 30m direct', 'Multiple daily flights', 'Window seat recommended'],
      },
      {
        type: 'hotel',
        title: 'Thamel Courtyard Hotel',
        desc: 'Quiet courtyard off the main drag, rooftop with mountain views when the haze clears.',
        price: '$45',
        per: 'per night',
        details: ['Central Thamel location', 'Trekking desk on-site', 'Breakfast included'],
      },
      {
        type: 'tour',
        title: 'Annapurna Base Camp Trek',
        desc: 'Ten days through rhododendron forest and stone villages to the foot of a mountain that makes you feel the right kind of small.',
        price: '$890',
        per: 'per person',
        details: ['10-day guided trek', 'Porter and guide included', 'All meals and teahouses'],
      },
    ],
  },

  Maldives: {
    name: 'Maldives',
    region: 'Asia',
    desc: 'Overwater bungalows, reefs five steps from your room, water the color of mouthwash. It is exactly as absurd and wonderful as the photos suggest.',
    imagePrompt: 'Landscape photography of Maldives overwater bungalows stretching over turquoise lagoon, white sand beach, coconut palms, crystal clear shallow water showing coral below, aerial perspective, warm afternoon light, 24mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Dubai to Male Direct',
        desc: 'Four hours south over the Indian Ocean, seaplane transfer to your atoll.',
        price: '$380',
        per: 'round trip',
        details: ['4h 10m nonstop', 'Emirates daily', 'Seaplane transfer extra'],
      },
      {
        type: 'hotel',
        title: 'Overwater Villa',
        desc: 'Glass floor panel above the reef, outdoor shower, butler who remembers your drink order.',
        price: '$650',
        per: 'per night',
        details: ['All-inclusive option', 'Private deck and ladder', 'Snorkel gear in-room'],
      },
      {
        type: 'tour',
        title: 'Sunset Dolphin Cruise',
        desc: 'Traditional dhoni boat, spinner dolphins by the dozen, champagne as the sun drops into the Indian Ocean.',
        price: '$95',
        per: 'per person',
        details: ['2-hour evening cruise', 'Drinks and canapes', 'Dolphin sighting guarantee'],
      },
    ],
  },

  'United States of America': {
    name: 'United States of America',
    region: 'Americas',
    desc: 'Grand Canyon to Greenwich Village. Redwood forests and neon diners. Too big to summarize, which is exactly the point.',
    imagePrompt: 'Landscape photography of Grand Canyon at sunset from South Rim, layered red and orange rock formations stretching to the horizon, Colorado River visible far below, dramatic clouds catching golden light, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'London to New York JFK',
        desc: 'Seven hours to the city that never figured out how to sleep.',
        price: '$450',
        per: 'round trip',
        details: ['7h nonstop', 'Multiple carriers daily', 'BA, Virgin, or Delta'],
      },
      {
        type: 'hotel',
        title: 'Midtown Manhattan Hotel',
        desc: 'Thirty-second floor, corner room, Times Square glow through the curtains.',
        price: '$245',
        per: 'per night',
        details: ['Theater District location', 'Rooftop bar', 'Subway two blocks away'],
      },
      {
        type: 'tour',
        title: 'Utah National Parks Loop',
        desc: 'Zion, Bryce, Arches, Canyonlands — five days of red rock and the kind of quiet that rings.',
        price: '$1,200',
        per: 'per person',
        details: ['5-day guided road trip', 'Camping and lodge mix', 'All park fees and meals'],
      },
    ],
  },

  Mexico: {
    name: 'Mexico',
    region: 'Americas',
    desc: 'Tacos from a cart at midnight that ruin all future tacos. Pyramids in the jungle. Oaxaca mezcal, sipped slow, smoke and agave.',
    imagePrompt: 'Landscape photography of Chichen Itza pyramid El Castillo at golden hour, ancient Mayan stone structure against dramatic sky, green lawn in foreground, warm directional light highlighting carved details, 28mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'Houston to Mexico City',
        desc: 'Two and a half hours to one of the largest cities on earth.',
        price: '$280',
        per: 'round trip',
        details: ['2h 30m nonstop', 'United or Aeromexico', 'Multiple daily departures'],
      },
      {
        type: 'hotel',
        title: 'Roma Norte Apartment',
        desc: 'Art deco building, tree-lined street, the best coffee shop in the city on the corner.',
        price: '$85',
        per: 'per night',
        details: ['Trendy Roma Norte', 'Full kitchen', 'Walking distance to Condesa'],
      },
      {
        type: 'tour',
        title: 'Oaxaca Mezcal and Markets',
        desc: 'Three distilleries, a market the size of a stadium, and mole with thirty-one ingredients.',
        price: '$145',
        per: 'per person',
        details: ['Full-day guided tour', 'All tastings and lunch', 'Hotel pickup included'],
      },
    ],
  },

  Brazil: {
    name: 'Brazil',
    region: 'Americas',
    desc: 'Christ the Redeemer with arms open and Copacabana stretching below. The Amazon at water level. Samba is not a performance here — it is a Tuesday.',
    imagePrompt: 'Landscape photography of Rio de Janeiro from Sugarloaf Mountain, Christ the Redeemer on Corcovado in distance, Guanabara Bay, city sprawl meeting green mountains and beaches, warm late afternoon light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Miami to Rio de Janeiro',
        desc: 'Overnight flight, land to warm Atlantic air and a caipirinha waiting.',
        price: '$620',
        per: 'round trip',
        details: ['8h 30m nonstop', 'LATAM Airlines', 'Night departure'],
      },
      {
        type: 'hotel',
        title: 'Ipanema Beachfront',
        desc: 'Ocean-view room, Dois Irmaos peaks framed in the window, sand between your toes in sixty seconds.',
        price: '$175',
        per: 'per night',
        details: ['Direct beach access', 'Rooftop pool', 'Breakfast included'],
      },
      {
        type: 'tour',
        title: 'Amazon Lodge Experience',
        desc: 'Six days on the river. Eco-lodge, naturalist guides, the kind of quiet you forget exists.',
        price: '$980',
        per: 'per person',
        details: ['6-day jungle lodge stay', 'All meals and excursions', 'Canoe and wildlife walks'],
      },
    ],
  },

  Argentina: {
    name: 'Argentina',
    region: 'Americas',
    desc: 'Steak grilled over wood for hours. Malbec in Mendoza. Glaciers calving into turquoise lakes. Buenos Aires stays up later than you.',
    imagePrompt: 'Landscape photography of Perito Moreno glacier in Patagonia Argentina, massive blue ice wall meeting turquoise Lago Argentino, jagged ice formations, Andes mountains in background, clear sky, 28mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'Dallas to Buenos Aires',
        desc: 'Nonstop on American, cross the equator while you sleep.',
        price: '$780',
        per: 'round trip',
        details: ['10h 30m nonstop', 'American Airlines', 'Lie-flat on select flights'],
      },
      {
        type: 'hotel',
        title: 'San Telmo Townhouse',
        desc: 'Converted tango-era mansion, cobblestone street, Sunday antique market outside your door.',
        price: '$95',
        per: 'per night',
        details: ['Historic San Telmo', 'Courtyard garden', 'Tango show weekly'],
      },
      {
        type: 'tour',
        title: 'Mendoza Wine and Andes',
        desc: 'Four wineries, Andes views from every tasting room, an asado lunch that goes three hours.',
        price: '$160',
        per: 'per person',
        details: ['Full-day wine tour', 'Four winery visits', 'Asado lunch with pairings'],
      },
    ],
  },

  Peru: {
    name: 'Peru',
    region: 'Americas',
    desc: 'Machu Picchu through the morning fog. Ceviche in Lima that changes how you think about fish. The Andes above, the Amazon below.',
    imagePrompt: 'Landscape photography of Machu Picchu at sunrise, ancient Incan stone citadel nestled between green mountain peaks, Huayna Picchu rising behind, clouds drifting through the ruins, golden morning light, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'Houston to Lima Direct',
        desc: 'Six hours south, ceviche for dinner, altitude the next morning.',
        price: '$480',
        per: 'round trip',
        details: ['6h 20m nonstop', 'United Airlines', 'Evening departure'],
      },
      {
        type: 'hotel',
        title: 'Cusco Colonial Inn',
        desc: 'Inca stone foundation, Spanish colonial above, oxygen canister by the bed for the altitude.',
        price: '$80',
        per: 'per night',
        details: ['Plaza de Armas area', 'Coca tea on arrival', 'Courtyard with fountain'],
      },
      {
        type: 'tour',
        title: 'Inca Trail Classic',
        desc: 'Four days through cloud forest and mountain passes, stone steps the Inca walked, arriving at Machu Picchu through the Sun Gate.',
        price: '$720',
        per: 'per person',
        details: ['4-day guided trek', 'Porter team and chef', 'Permits and entry included'],
      },
    ],
  },

  'Costa Rica': {
    name: 'Costa Rica',
    region: 'Americas',
    desc: 'Sloths in the canopy, volcanoes steaming through cloud forest, surf breaks on both oceans. Small country, absurd biodiversity.',
    imagePrompt: 'Landscape photography of Arenal Volcano in Costa Rica rising above dense tropical rainforest, conical shape with wisp of cloud at summit, La Fortuna waterfall area, lush green vegetation, late afternoon light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Atlanta to San Jose Direct',
        desc: 'Three and a half hours to Central America — shorter than most domestic flights.',
        price: '$340',
        per: 'round trip',
        details: ['3h 40m nonstop', 'Delta daily', 'Year-round service'],
      },
      {
        type: 'hotel',
        title: 'Arenal Rainforest Lodge',
        desc: 'Volcano from your hot spring, howler monkeys as alarm clocks, toucans at breakfast.',
        price: '$145',
        per: 'per night',
        details: ['Volcano view rooms', 'Hot springs on-site', 'Nature trails included'],
      },
      {
        type: 'tour',
        title: 'Monteverde Cloud Forest Trek',
        desc: 'Hanging bridges above the canopy, a guide who spots birds you would walk right past.',
        price: '$95',
        per: 'per person',
        details: ['Half-day guided hike', 'Hanging bridges circuit', 'Transport from Arenal'],
      },
    ],
  },

  Colombia: {
    name: 'Colombia',
    region: 'Americas',
    desc: 'Cartagena walls hold centuries of heat. Coffee country roads wind through green mountains. The salsa in Cali is not optional — your feet decide for you.',
    imagePrompt: 'Landscape photography of Cartagena old town Colombia, colorful colonial buildings in yellow, blue, and orange, bougainvillea cascading over balconies, narrow cobblestone street, church dome in background, warm afternoon light, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Fort Lauderdale to Cartagena',
        desc: 'Two hours and forty minutes to the Caribbean coast of South America.',
        price: '$290',
        per: 'round trip',
        details: ['2h 40m nonstop', 'JetBlue or Spirit', 'Year-round daily'],
      },
      {
        type: 'hotel',
        title: 'Walled City Boutique',
        desc: 'Colonial courtyard, plunge pool, ceviche delivered to your hammock.',
        price: '$130',
        per: 'per night',
        details: ['Inside the walled city', 'Rooftop pool and bar', 'Breakfast included'],
      },
      {
        type: 'tour',
        title: 'Coffee Triangle Finca Stay',
        desc: 'Pick beans, roast them, drink them — all before lunch, all in the same valley.',
        price: '$220',
        per: 'per person',
        details: ['2-day coffee region trip', 'Finca accommodation', 'All meals and tours'],
      },
    ],
  },

  Morocco: {
    name: 'Morocco',
    region: 'Africa',
    desc: 'Marrakech medina: leather, spice, someone grilling lamb around the corner. Atlas Mountains by afternoon. Sahara dunes by tomorrow.',
    imagePrompt: 'Landscape photography of Sahara Desert Morocco, orange sand dunes with dramatic shadows and ripple patterns, camel caravan silhouetted on ridge, warm golden sunset light, vast empty sky, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Paris to Marrakech Direct',
        desc: 'Three hours from Europe to Africa, easy as taking a bus.',
        price: '$180',
        per: 'round trip',
        details: ['3h 15m nonstop', 'RAM or Air France', 'Multiple daily flights'],
      },
      {
        type: 'hotel',
        title: 'Medina Riad',
        desc: 'Tiled courtyard, plunge pool, a rooftop where you can see the Atlas Mountains and the minaret.',
        price: '$95',
        per: 'per night',
        details: ['Central medina location', 'Traditional hammam', 'Moroccan breakfast daily'],
      },
      {
        type: 'tour',
        title: 'Sahara Desert Overnight',
        desc: 'Camel trek to a camp in the Erg Chebbi dunes, Berber drums after dinner, stars you forgot existed.',
        price: '$190',
        per: 'per person',
        details: ['2-day desert excursion', 'Camel ride and camp dinner', 'Berber tent accommodation'],
      },
    ],
  },

  'South Africa': {
    name: 'South Africa',
    region: 'Africa',
    desc: 'Table Mountain flat as a blade above Cape Town. Penguins on the beach, vineyards in the valley, the Big Five two hours north.',
    imagePrompt: 'Landscape photography of Cape Town with Table Mountain, flat-topped mountain towering over city, V&A Waterfront harbor in foreground, clear blue sky with thin tablecloth cloud, 28mm wide angle, golden hour',
    offers: [
      {
        type: 'flight',
        title: 'Atlanta to Johannesburg',
        desc: 'Nonstop overnight on Delta, sixteen hours but flat beds make it bearable.',
        price: '$890',
        per: 'round trip',
        details: ['16h nonstop', 'Delta direct', 'Flat bed in business'],
      },
      {
        type: 'hotel',
        title: 'Cape Town Waterfront Hotel',
        desc: 'Harbor view, Table Mountain filling the other window, penguins at Boulders Beach thirty minutes south.',
        price: '$160',
        per: 'per night',
        details: ['V&A Waterfront', 'Pool and spa', 'Walking distance to restaurants'],
      },
      {
        type: 'tour',
        title: 'Kruger Safari Drive',
        desc: 'Three days in open Land Rovers, tracking leopards and lions with rangers who read the bush like a book.',
        price: '$1,100',
        per: 'per person',
        details: ['3-day safari package', 'Private game reserve', 'All meals and game drives'],
      },
    ],
  },

  Kenya: {
    name: 'Kenya',
    region: 'Africa',
    desc: 'The Masai Mara at dawn — a million wildebeest, a few lions watching. Nairobi is faster than you think. The coast has Swahili ruins and dhow sails.',
    imagePrompt: 'Landscape photography of Masai Mara savanna at sunrise, vast golden grassland, scattered acacia trees, herd of wildebeest in distance, hot air balloon rising on the horizon, warm light, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'London to Nairobi Direct',
        desc: 'Overnight on Kenya Airways or BA, arrive in time for a morning game drive.',
        price: '$640',
        per: 'round trip',
        details: ['8h 30m nonstop', 'Kenya Airways or BA', 'Night departure'],
      },
      {
        type: 'hotel',
        title: 'Masai Mara Tented Camp',
        desc: 'Canvas walls, proper bed, a hippo in the river outside that you hear all night.',
        price: '$280',
        per: 'per night',
        details: ['Inside the Mara reserve', 'Two game drives daily', 'Full board included'],
      },
      {
        type: 'tour',
        title: 'Great Migration Safari',
        desc: 'Four days following the herds, river crossings if the timing is right, sundowners on the savanna.',
        price: '$1,400',
        per: 'per person',
        details: ['4-day guided safari', 'Light aircraft transfers', 'All meals and game drives'],
      },
    ],
  },

  Tanzania: {
    name: 'Tanzania',
    region: 'Africa',
    desc: 'Kilimanjaro at sunrise, Serengeti to the horizon, Zanzibar spice markets and turquoise shallows. The continent at its most concentrated.',
    imagePrompt: 'Landscape photography of Mount Kilimanjaro at dawn from Amboseli, snow-capped peak rising above savanna plains, elephants silhouetted in foreground, pink and orange sky, 85mm telephoto lens',
    offers: [
      {
        type: 'flight',
        title: 'Amsterdam to Kilimanjaro',
        desc: 'KLM direct, land at the foot of the tallest freestanding mountain on earth.',
        price: '$720',
        per: 'round trip',
        details: ['9h nonstop', 'KLM direct', 'Night departure'],
      },
      {
        type: 'hotel',
        title: 'Zanzibar Beach House',
        desc: 'Dhow-sail shade, spice-garden walls, tide goes out half a mile and leaves warm pools.',
        price: '$120',
        per: 'per night',
        details: ['North coast Nungwi', 'Beachfront bungalow', 'Seafood dinners available'],
      },
      {
        type: 'tour',
        title: 'Serengeti and Ngorongoro',
        desc: 'Five days between the crater and the plains, more animals per square mile than anywhere on the planet.',
        price: '$1,600',
        per: 'per person',
        details: ['5-day camping safari', 'All park fees and meals', 'Professional guide and cook'],
      },
    ],
  },

  Egypt: {
    name: 'Egypt',
    region: 'Middle East',
    desc: 'The pyramids are right there, at the edge of the city, older than almost everything. The Nile at sunset. Luxor temples lit gold at night.',
    imagePrompt: 'Landscape photography of Giza Pyramids at golden hour, three pyramids in alignment with Sphinx in foreground, warm desert light, clear sky with slight haze, Cairo skyline faintly visible in background, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'JFK to Cairo Nonstop',
        desc: 'Eleven hours direct on EgyptAir, pyramids visible from the approach.',
        price: '$580',
        per: 'round trip',
        details: ['11h nonstop', 'EgyptAir', 'Two meals served'],
      },
      {
        type: 'hotel',
        title: 'Giza Pyramid View Hotel',
        desc: 'Rooftop pool, the Great Pyramid filling the frame, sound and light show from your balcony.',
        price: '$110',
        per: 'per night',
        details: ['Direct pyramid views', 'Rooftop restaurant', 'Tour desk on-site'],
      },
      {
        type: 'tour',
        title: 'Nile Felucca Cruise',
        desc: 'Four days by traditional sailboat, Luxor to Aswan, temples on both banks, sleeping on deck.',
        price: '$420',
        per: 'per person',
        details: ['4-day sailing cruise', 'All meals on board', 'Temple visits included'],
      },
    ],
  },

  Jordan: {
    name: 'Jordan',
    region: 'Middle East',
    desc: 'Petra carved from rose-red cliffs. Wadi Rum like Mars with better hospitality. The Dead Sea, where floating is not a choice but a fact.',
    imagePrompt: 'Landscape photography of Petra Treasury Al-Khazneh seen through the narrow Siq canyon, rose-red carved facade lit by warm reflected light, tiny figures at base for scale, sandstone walls towering on both sides, 24mm lens',
    offers: [
      {
        type: 'flight',
        title: 'Chicago to Amman via Istanbul',
        desc: 'Quick connection through Istanbul, touch down in the Hashemite Kingdom by morning.',
        price: '$640',
        per: 'round trip',
        details: ['One-stop via Istanbul', 'Total 14h', 'Turkish Airlines'],
      },
      {
        type: 'hotel',
        title: 'Wadi Rum Desert Camp',
        desc: 'Bedouin tent with a real bed, red sand in every direction, stars so dense they look solid.',
        price: '$85',
        per: 'per night',
        details: ['Private tent with bathroom', 'Dinner and breakfast included', 'Jeep tour of Wadi Rum'],
      },
      {
        type: 'tour',
        title: 'Petra by Night Walk',
        desc: 'The Siq lit by fifteen hundred candles, the Treasury glowing at the end — no photograph does it justice.',
        price: '$75',
        per: 'per person',
        details: ['Evening walking tour', 'Candlelit Siq experience', 'Bedouin tea and music'],
      },
    ],
  },

  'United Arab Emirates': {
    name: 'United Arab Emirates',
    region: 'Middle East',
    desc: 'Dubai built a skyline from sand in thirty years. The desert starts where the mall ends. Abu Dhabi is quieter, and the Louvre is on an island.',
    imagePrompt: 'Landscape photography of Dubai skyline at blue hour, Burj Khalifa towering above surrounding skyscrapers, city lights reflecting in Dubai Creek, desert haze on horizon, 50mm lens',
    offers: [
      {
        type: 'flight',
        title: 'JFK to Dubai Nonstop',
        desc: 'Emirates flagship route, fourteen hours with the best in-flight entertainment in the sky.',
        price: '$720',
        per: 'round trip',
        details: ['14h nonstop', 'Emirates A380', 'ICE entertainment system'],
      },
      {
        type: 'hotel',
        title: 'Marina Tower Suite',
        desc: 'Fifty-third floor, floor-to-ceiling glass, the Palm and the Gulf from one corner.',
        price: '$210',
        per: 'per night',
        details: ['Dubai Marina', 'Infinity pool on 55th floor', 'Beach club access'],
      },
      {
        type: 'tour',
        title: 'Desert Safari and Dinner',
        desc: 'Dune bashing in a Land Cruiser, sunset from a high dune, shisha and lamb under the stars.',
        price: '$130',
        per: 'per person',
        details: ['Half-day evening tour', 'BBQ dinner in desert camp', 'Camel ride and sandboarding'],
      },
    ],
  },

  Australia: {
    name: 'Australia',
    region: 'Oceania',
    desc: 'Opera House from your pillow, Harbour Bridge from the bar. The Outback is old in a way that makes your bones know it. The reef is still there — go now.',
    imagePrompt: 'Landscape photography of Sydney Opera House and Harbour Bridge at sunset, white sail shapes and steel arch reflected in harbor water, ferries crossing, warm golden light, shot from Mrs Macquaries Chair, 35mm lens',
    offers: [
      {
        type: 'flight',
        title: 'LAX to Sydney Nonstop',
        desc: 'Fifteen hours over the Pacific, cross the date line, lose a day, gain a continent.',
        price: '$950',
        per: 'round trip',
        details: ['15h nonstop', 'Qantas or United', 'Two meals and snack'],
      },
      {
        type: 'hotel',
        title: 'Circular Quay Hotel',
        desc: 'Harbor-view room, Opera House lit white at night, morning ferry to Manly from the dock below.',
        price: '$220',
        per: 'per night',
        details: ['Circular Quay waterfront', 'Harbour view rooms', 'Walking distance to The Rocks'],
      },
      {
        type: 'tour',
        title: 'Great Barrier Reef Dive',
        desc: 'Catamaran to the outer reef, two dives or three snorkels, coral gardens and sea turtles at arm\'s length.',
        price: '$240',
        per: 'per person',
        details: ['Full day from Cairns', 'All gear and instruction', 'Marine biologist on board'],
      },
    ],
  },

  'New Zealand': {
    name: 'New Zealand',
    region: 'Oceania',
    desc: 'Fjords in the south, volcanoes in the north, sheep in between. A country that fits in Montana but packs in more landscapes than most continents.',
    imagePrompt: 'Landscape photography of Milford Sound New Zealand, towering Mitre Peak reflected in calm fjord water, lush green rainforest on steep cliffs, waterfall cascading into the sound, moody clouds, 24mm wide angle',
    offers: [
      {
        type: 'flight',
        title: 'San Francisco to Auckland',
        desc: 'Twelve hours direct on Air New Zealand, land in Middle-earth by morning.',
        price: '$880',
        per: 'round trip',
        details: ['12h 30m nonstop', 'Air New Zealand', 'Skycouch option available'],
      },
      {
        type: 'hotel',
        title: 'Queenstown Lakefront',
        desc: 'Lake Wakatipu, the Remarkables behind it, a town built for people who jump off things.',
        price: '$190',
        per: 'per night',
        details: ['Lakefront location', 'Mountain views', 'Adventure desk on-site'],
      },
      {
        type: 'tour',
        title: 'Milford Sound Overnight',
        desc: 'Cruise into the fjord, waterfalls on both sides, anchor for the night and wake up in silence.',
        price: '$380',
        per: 'per person',
        details: ['Overnight cruise', 'All meals on board', 'Kayaking excursion included'],
      },
    ],
  },
};
