export const IMAGE_MAP = {
  "France": "images/france.jpg",
  "Italy": "images/italy.jpg",
  "Spain": "images/spain.jpg",
  "Portugal": "images/portugal.jpg",
  "Greece": "images/greece.jpg",
  "Switzerland": "images/switzerland.jpg",
  "Croatia": "images/croatia.jpg",
  "Iceland": "images/iceland.jpg",
  "Norway": "images/norway.jpg",
  "Ireland": "images/ireland.jpg",
  "Czech Republic": "images/czech-republic.jpg",
  "Turkey": "images/turkey.jpg",
  "Germany": "images/germany.jpg",
  "United Kingdom": "images/united-kingdom.jpg",
  "Netherlands": "images/netherlands.jpg",
  "Austria": "images/austria.jpg",
  "Sweden": "images/sweden.jpg",
  "Denmark": "images/denmark.jpg",
  "Poland": "images/poland.jpg",
  "Hungary": "images/hungary.jpg",
  "Belgium": "images/belgium.jpg",
  "Finland": "images/finland.jpg",
  "Montenegro": "images/montenegro.jpg",
  "Slovenia": "images/slovenia.jpg",
  "Japan": "images/japan.jpg",
  "Thailand": "images/thailand.jpg",
  "Vietnam": "images/vietnam.jpg",
  "Indonesia": "images/indonesia.jpg",
  "India": "images/india.jpg",
  "South Korea": "images/south-korea.jpg",
  "Sri Lanka": "images/sri-lanka.jpg",
  "Nepal": "images/nepal.jpg",
  "Maldives": "images/maldives.jpg",
  "United States of America": "images/united-states-of-america.jpg",
  "Mexico": "images/mexico.jpg",
  "Brazil": "images/brazil.jpg",
  "Argentina": "images/argentina.jpg",
  "Peru": "images/peru.jpg",
  "Costa Rica": "images/costa-rica.jpg",
  "Colombia": "images/colombia.jpg",
  "Morocco": "images/morocco.jpg",
  "South Africa": "images/south-africa.jpg",
  "Kenya": "images/kenya.jpg",
  "Tanzania": "images/tanzania.jpg",
  "Egypt": "images/egypt.jpg",
  "Jordan": "images/jordan.jpg",
  "United Arab Emirates": "images/united-arab-emirates.jpg",
  "Australia": "images/australia.jpg",
  "New Zealand": "images/new-zealand.jpg"
};
